<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Jobs\ImportBorderEntityJob;
use Illuminate\Console\Command;

class ImportBordersCommand extends Command
{
    protected $signature = 'pipeline:import-borders
        {path : Path to JSONL file generated by python -m pipeline borders}
        {--sync : Process synchronously instead of dispatching jobs}
        {--force : Overwrite existing entities}
        {--batch-id= : Custom batch identifier (default: auto-generated)}';

    protected $description = 'Import OHM border entities from pipeline JSONL output';

    public function handle(): int
    {
        $path = (string) $this->argument('path');

        if (! is_file($path)) {
            $this->error("File not found: {$path}");

            return self::FAILURE;
        }

        $sync = (bool) $this->option('sync');
        $force = (bool) $this->option('force');
        $batchId = $this->option('batch-id') ?? 'borders-'.now()->format('Ymd-His');

        $this->info("Batch: {$batchId}");

        $handle = fopen($path, 'r');
        if ($handle === false) {
            $this->error("Cannot open file: {$path}");

            return self::FAILURE;
        }

        $imported = 0;
        $skippedMalformed = 0;

        try {
            while (($line = fgets($handle)) !== false) {
                $line = trim($line);
                if ($line === '') {
                    continue;
                }

                $record = json_decode($line, true);
                if (! is_array($record)) {
                    $skippedMalformed++;

                    continue;
                }

                if ($sync) {
                    (new ImportBorderEntityJob($record, $batchId, $force))->handle();
                } else {
                    ImportBorderEntityJob::dispatch($record, $batchId, $force);
                }

                $imported++;
            }
        } finally {
            fclose($handle);
        }

        $this->info("Dispatched: {$imported} | Skipped malformed: {$skippedMalformed}");

        return self::SUCCESS;
    }
}
