<?php

declare(strict_types=1);

namespace Database\Seeders;

use Database\Seeders\Traits\PgArrayLiteral;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CalendarSystemSeeder extends Seeder
{
    use PgArrayLiteral;

    public function run(): void
    {
        $table = 'ref_calendar_systems';

        DB::table($table)->truncate();

        $calendars = [
            [
                'name' => 'Gregorian',
                'code' => 'gregorian',
                'calendar_type' => 'solar',
                'epoch_description' => 'Birth of Christ (1 CE)',
                'epoch_gregorian' => '0001-01-01',
                'conversion_formula' => 'Identity — this is the reference calendar',
                'conversion_notes' => null,
                'used_by_regions' => $this->textArray(['Global']),
                'used_by_periods' => $this->textArray(['Modern']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Julian',
                'code' => 'julian',
                'calendar_type' => 'solar',
                'epoch_description' => 'Same as Gregorian but different leap year rules',
                'epoch_gregorian' => '0001-01-01',
                'conversion_formula' => 'Gregorian date = Julian date + accumulated leap day difference (13 days as of 21st century)',
                'conversion_notes' => 'Adopted 46 BCE; replaced by Gregorian in 1582 in Catholic Europe, much later in Orthodox and Protestant regions. Russia adopted Gregorian only in 1918.',
                'used_by_regions' => $this->textArray(['Europe', 'Mediterranean']),
                'used_by_periods' => $this->textArray(['Roman Republic', 'Roman Empire', 'Medieval', 'Early Modern']),
                'still_in_use' => false,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Islamic (Hijri)',
                'code' => 'hijri',
                'calendar_type' => 'lunar',
                'epoch_description' => 'Migration of Muhammad to Medina, 622 CE',
                'epoch_gregorian' => '0622-07-16',
                'conversion_formula' => 'Approximate: Gregorian ≈ Hijri × 0.970 + 622. Exact conversion requires tabular lunar calculations.',
                'conversion_notes' => 'Purely lunar — 354 or 355 days per year. Months drift through seasons. Different communities may observe different start dates for months (sighting vs calculation).',
                'used_by_regions' => $this->textArray(['Middle East', 'North Africa', 'South Asia', 'Southeast Asia']),
                'used_by_periods' => $this->textArray(['Medieval Islamic', 'Ottoman', 'Modern Islamic']),
                'still_in_use' => true,
                'month_names' => json_encode([
                    ['number' => 1, 'name' => 'Muharram', 'days' => 30],
                    ['number' => 2, 'name' => 'Safar', 'days' => 29],
                    ['number' => 3, 'name' => 'Rabi al-Awwal', 'days' => 30],
                    ['number' => 4, 'name' => 'Rabi al-Thani', 'days' => 29],
                    ['number' => 5, 'name' => 'Jumada al-Ula', 'days' => 30],
                    ['number' => 6, 'name' => 'Jumada al-Thani', 'days' => 29],
                    ['number' => 7, 'name' => 'Rajab', 'days' => 30],
                    ['number' => 8, 'name' => "Sha'ban", 'days' => 29],
                    ['number' => 9, 'name' => 'Ramadan', 'days' => 30],
                    ['number' => 10, 'name' => 'Shawwal', 'days' => 29],
                    ['number' => 11, 'name' => "Dhu al-Qi'dah", 'days' => 30],
                    ['number' => 12, 'name' => 'Dhu al-Hijjah', 'days' => 29],
                ]),
                'special_cycles' => null,
            ],
            [
                'name' => 'Hebrew',
                'code' => 'hebrew',
                'calendar_type' => 'lunisolar',
                'epoch_description' => 'Creation of the world according to Jewish tradition (3761 BCE)',
                'epoch_gregorian' => '-3761-01-01',
                'conversion_formula' => 'Complex — lunisolar with 19-year Metonic cycle. Libraries like hebcal handle conversion.',
                'conversion_notes' => 'Leap months (Adar II) added 7 times per 19-year cycle. Day starts at sunset.',
                'used_by_regions' => $this->textArray(['Middle East', 'Europe', 'Global diaspora']),
                'used_by_periods' => $this->textArray(['Ancient', 'Medieval', 'Modern']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => '19-year Metonic cycle',
            ],
            [
                'name' => 'Chinese (Sexagenary Cycle)',
                'code' => 'chinese_era',
                'calendar_type' => 'lunisolar',
                'epoch_description' => 'Varies by dynasty; traditional dating begins with Yellow Emperor',
                'epoch_gregorian' => null,
                'conversion_formula' => 'Complex lunisolar calculation with astronomical observations. Era names changed with each emperor.',
                'conversion_notes' => 'Multiple era names per emperor possible. Requires both era name and year number for conversion.',
                'used_by_regions' => $this->textArray(['East Asia']),
                'used_by_periods' => $this->textArray(['Imperial China', 'Medieval', 'Early Modern']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => '60-year sexagenary cycle (Heavenly Stems × Earthly Branches); 12-year animal cycle',
            ],
            [
                'name' => 'Roman (AUC)',
                'code' => 'auc',
                'calendar_type' => 'solar',
                'epoch_description' => 'Founding of Rome (753 BCE)',
                'epoch_gregorian' => '-0753-04-21',
                'conversion_formula' => 'Gregorian year = AUC year - 753',
                'conversion_notes' => 'Ab urbe condita — from the founding of the city. Used alongside consular dating.',
                'used_by_regions' => $this->textArray(['Roman Empire', 'Mediterranean']),
                'used_by_periods' => $this->textArray(['Roman Republic', 'Roman Empire']),
                'still_in_use' => false,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Egyptian Civil',
                'code' => 'egyptian',
                'calendar_type' => 'solar',
                'epoch_description' => 'Various; typically regnal years of pharaoh',
                'epoch_gregorian' => null,
                'conversion_formula' => '365 days exactly, no leap year. Drifts 1 day every 4 years relative to solar year.',
                'conversion_notes' => 'Three seasons of 4 months × 30 days + 5 epagomenal days. Called "wandering year" because it drifts.',
                'used_by_regions' => $this->textArray(['Egypt']),
                'used_by_periods' => $this->textArray(['Ancient Egyptian', 'Ptolemaic']),
                'still_in_use' => false,
                'month_names' => null,
                'special_cycles' => '1461-year Sothic cycle (when New Year realigns with heliacal rising of Sirius)',
            ],
            [
                'name' => 'Seleucid Era',
                'code' => 'seleucid',
                'calendar_type' => 'solar',
                'epoch_description' => 'Foundation of the Seleucid Empire (312 BCE)',
                'epoch_gregorian' => '-0312-01-01',
                'conversion_formula' => 'Gregorian year = Seleucid year - 311 (approximately)',
                'conversion_notes' => 'Used widely in the Near East, even after Seleucid political power waned. Some Jewish communities used it until the 16th century.',
                'used_by_regions' => $this->textArray(['Near East', 'Central Asia']),
                'used_by_periods' => $this->textArray(['Hellenistic', 'Parthian', 'Late Antiquity']),
                'still_in_use' => false,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Regnal Years',
                'code' => 'regnal',
                'calendar_type' => 'variable',
                'epoch_description' => 'Accession date of the current ruler',
                'epoch_gregorian' => null,
                'conversion_formula' => 'Year N of King X = accession date of X + N years. Requires knowing each ruler\'s accession date.',
                'conversion_notes' => 'Universal practice in nearly all monarchies. Regnal years may not align with calendar year start. Interregna create gaps.',
                'used_by_regions' => $this->textArray(['Global']),
                'used_by_periods' => $this->textArray(['All monarchical periods']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Olympiad Dating',
                'code' => 'olympiad',
                'calendar_type' => 'cyclical',
                'epoch_description' => 'First Olympic Games (776 BCE)',
                'epoch_gregorian' => '-0776-01-01',
                'conversion_formula' => 'Gregorian year ≈ (Olympiad - 1) × 4 + year_in_olympiad - 776',
                'conversion_notes' => 'Used by Greek historians. Each Olympiad = 4 years. Year 1 of Olympiad 1 = 776 BCE.',
                'used_by_regions' => $this->textArray(['Greece', 'Hellenistic world']),
                'used_by_periods' => $this->textArray(['Classical Greece', 'Hellenistic']),
                'still_in_use' => false,
                'month_names' => null,
                'special_cycles' => '4-year Olympic cycle',
            ],
            [
                'name' => 'Indiction Cycle',
                'code' => 'indiction',
                'calendar_type' => 'cyclical',
                'epoch_description' => 'First Indiction (312 CE)',
                'epoch_gregorian' => '0312-01-01',
                'conversion_formula' => 'Indiction number = (Gregorian year + 3) mod 15. Does not uniquely identify a year — only position in 15-year cycle.',
                'conversion_notes' => 'Originally a Roman tax assessment cycle. Widely used in Byzantine Empire and medieval Europe for dating documents. Must be combined with other information to determine exact year.',
                'used_by_regions' => $this->textArray(['Byzantine Empire', 'Medieval Europe']),
                'used_by_periods' => $this->textArray(['Late Roman', 'Byzantine', 'Medieval']),
                'still_in_use' => false,
                'month_names' => null,
                'special_cycles' => '15-year indiction cycle',
            ],
            [
                'name' => 'Buddhist Era',
                'code' => 'buddhist',
                'calendar_type' => 'solar',
                'epoch_description' => 'Death (parinibbana) of the Buddha (543 BCE)',
                'epoch_gregorian' => '-0543-01-01',
                'conversion_formula' => 'Gregorian year = Buddhist year - 543',
                'conversion_notes' => 'Official calendar of Thailand (since 1940). Myanmar uses a variant.',
                'used_by_regions' => $this->textArray(['Southeast Asia', 'Sri Lanka']),
                'used_by_periods' => $this->textArray(['Classical', 'Medieval', 'Modern']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Vikram Samvat',
                'code' => 'vikram',
                'calendar_type' => 'lunisolar',
                'epoch_description' => 'Traditionally 57 BCE, commemorating King Vikramaditya',
                'epoch_gregorian' => '-0057-01-01',
                'conversion_formula' => 'Gregorian year ≈ Vikram year - 57',
                'conversion_notes' => 'Official calendar of Nepal. Widely used in northern India.',
                'used_by_regions' => $this->textArray(['South Asia']),
                'used_by_periods' => $this->textArray(['Classical', 'Medieval', 'Modern']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Saka Era',
                'code' => 'saka',
                'calendar_type' => 'solar',
                'epoch_description' => '78 CE, associated with Kanishka or the Saka rulers',
                'epoch_gregorian' => '0078-01-01',
                'conversion_formula' => 'Gregorian year = Saka year + 78',
                'conversion_notes' => 'Basis of the Indian National Calendar (adopted 1957).',
                'used_by_regions' => $this->textArray(['India', 'Southeast Asia']),
                'used_by_periods' => $this->textArray(['Classical', 'Medieval', 'Modern']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => null,
            ],
            [
                'name' => 'Ethiopian',
                'code' => 'ethiopian',
                'calendar_type' => 'solar',
                'epoch_description' => 'Approximately 8 years behind Gregorian (based on alternate Annunciation calculation)',
                'epoch_gregorian' => '0008-01-01',
                'conversion_formula' => 'Gregorian year ≈ Ethiopian year + 7 or 8 (depending on month)',
                'conversion_notes' => '13 months: 12 months of 30 days + 1 month of 5 or 6 days (Pagume). New Year on September 11/12 Gregorian.',
                'used_by_regions' => $this->textArray(['Ethiopia', 'Eritrea']),
                'used_by_periods' => $this->textArray(['All periods']),
                'still_in_use' => true,
                'month_names' => null,
                'special_cycles' => null,
            ],
        ];

        foreach ($calendars as $calendar) {
            DB::table($table)->insert($calendar);
        }
    }
}
