<?php

declare(strict_types=1);

namespace Database\Seeders;

use Database\Seeders\Traits\PgArrayLiteral;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GeographicRegionSeeder extends Seeder
{
    use PgArrayLiteral;

    public function run(): void
    {
        $table = 'ref_geographic_regions';

        // Disable FK checks for batch insert ordering
        DB::statement('ALTER TABLE ref_geographic_regions DISABLE TRIGGER ALL');
        DB::table($table)->truncate();

        $regions = $this->buildRegionTree();
        $sort = 0;

        foreach ($regions as $region) {
            $region['sort_order'] = ++$sort;
            DB::table($table)->insert($region);
        }

        DB::statement('ALTER TABLE ref_geographic_regions ENABLE TRIGGER ALL');
    }

    /**
     * Build the full region hierarchy as flat rows with parent_region_id references.
     * IDs are hardcoded so other seeders can reference them.
     *
     * @return array<int, array<string, mixed>>
     */
    private function buildRegionTree(): array
    {
        return [
            // ── Depth 0: World ─────────────────────────────────────
            [
                'region_id' => 1,
                'name' => 'World',
                'alternative_names' => null,
                'parent_region_id' => null,
                'depth_level' => 0,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 0,
            ],

            // ── Depth 0: Continents ────────────────────────────────
            [
                'region_id' => 2,
                'name' => 'Africa',
                'alternative_names' => $this->textArray(['Libya (ancient Greek)', 'Ifriqiya']),
                'parent_region_id' => 1,
                'depth_level' => 0,
                'modern_countries' => null,
                'historical_names' => $this->textArray(['Libya', 'Ifriqiya']),
                'typical_periods' => null,
                'batch_priority' => 5,
            ],
            [
                'region_id' => 3,
                'name' => 'Europe',
                'alternative_names' => null,
                'parent_region_id' => 1,
                'depth_level' => 0,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 10,
            ],
            [
                'region_id' => 4,
                'name' => 'Asia',
                'alternative_names' => null,
                'parent_region_id' => 1,
                'depth_level' => 0,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 10,
            ],
            [
                'region_id' => 5,
                'name' => 'Americas',
                'alternative_names' => $this->textArray(['New World']),
                'parent_region_id' => 1,
                'depth_level' => 0,
                'modern_countries' => null,
                'historical_names' => $this->textArray(['New World', 'The Indies']),
                'typical_periods' => null,
                'batch_priority' => 3,
            ],
            [
                'region_id' => 6,
                'name' => 'Oceania',
                'alternative_names' => null,
                'parent_region_id' => 1,
                'depth_level' => 0,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 1,
            ],
            [
                'region_id' => 7,
                'name' => 'Oceans and Maritime Zones',
                'alternative_names' => null,
                'parent_region_id' => 1,
                'depth_level' => 0,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 2,
            ],

            // ── Africa: Sub-continental (depth 1) ──────────────────
            [
                'region_id' => 10,
                'name' => 'North Africa',
                'alternative_names' => null,
                'parent_region_id' => 2,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Egypt', 'Libya', 'Tunisia', 'Algeria', 'Morocco']),
                'historical_names' => $this->textArray(['Africa (Roman province)', 'Barbary Coast']),
                'typical_periods' => $this->textArray(['Ancient', 'Classical Antiquity', 'Medieval Islamic']),
                'batch_priority' => 8,
            ],
            [
                'region_id' => 11,
                'name' => 'West Africa',
                'alternative_names' => null,
                'parent_region_id' => 2,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Nigeria', 'Ghana', 'Mali', 'Senegal', 'Niger']),
                'historical_names' => $this->textArray(['Sudan (historical)', 'Guinea']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 4,
            ],
            [
                'region_id' => 12,
                'name' => 'East Africa',
                'alternative_names' => null,
                'parent_region_id' => 2,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Ethiopia', 'Somalia', 'Kenya', 'Tanzania']),
                'historical_names' => $this->textArray(['Abyssinia', 'Azania']),
                'typical_periods' => $this->textArray(['Ancient', 'Medieval']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 13,
                'name' => 'Central Africa',
                'alternative_names' => null,
                'parent_region_id' => 2,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['DR Congo', 'Cameroon', 'Central African Republic']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 1,
            ],
            [
                'region_id' => 14,
                'name' => 'Southern Africa',
                'alternative_names' => null,
                'parent_region_id' => 2,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['South Africa', 'Zimbabwe', 'Mozambique', 'Botswana']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 2,
            ],

            // ── Africa: Regional (depth 2) ─────────────────────────
            [
                'region_id' => 15,
                'name' => 'Egypt and Nile Valley',
                'alternative_names' => $this->textArray(['Kemet', 'Aegyptus']),
                'parent_region_id' => 10,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Egypt', 'Sudan']),
                'historical_names' => $this->textArray(['Kemet', 'Aegyptus', 'Misr']),
                'typical_periods' => $this->textArray(['Ancient', 'Hellenistic', 'Roman', 'Islamic']),
                'batch_priority' => 10,
            ],
            [
                'region_id' => 16,
                'name' => 'Maghreb',
                'alternative_names' => null,
                'parent_region_id' => 10,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Morocco', 'Algeria', 'Tunisia', 'Libya']),
                'historical_names' => $this->textArray(['Numidia', 'Mauretania', 'Ifriqiya']),
                'typical_periods' => $this->textArray(['Roman', 'Medieval Islamic']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 17,
                'name' => 'Sahara',
                'alternative_names' => null,
                'parent_region_id' => 10,
                'depth_level' => 2,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Prehistoric', 'Medieval']),
                'batch_priority' => 1,
            ],
            [
                'region_id' => 18,
                'name' => 'Sahel',
                'alternative_names' => null,
                'parent_region_id' => 11,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Mali', 'Niger', 'Burkina Faso', 'Chad']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 19,
                'name' => 'Guinea Coast',
                'alternative_names' => null,
                'parent_region_id' => 11,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Ghana', 'Nigeria', 'Benin', 'Togo', 'Ivory Coast']),
                'historical_names' => $this->textArray(['Gold Coast', 'Slave Coast']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern', 'Colonial']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 20,
                'name' => 'Niger River Basin',
                'alternative_names' => null,
                'parent_region_id' => 11,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Mali', 'Nigeria', 'Niger']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 2,
            ],
            [
                'region_id' => 21,
                'name' => 'Horn of Africa',
                'alternative_names' => null,
                'parent_region_id' => 12,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Ethiopia', 'Somalia', 'Eritrea', 'Djibouti']),
                'historical_names' => $this->textArray(['Punt', 'Abyssinia']),
                'typical_periods' => $this->textArray(['Ancient', 'Medieval']),
                'batch_priority' => 4,
            ],
            [
                'region_id' => 22,
                'name' => 'Great Lakes Region',
                'alternative_names' => null,
                'parent_region_id' => 12,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Uganda', 'Rwanda', 'Burundi', 'DR Congo']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 1,
            ],
            [
                'region_id' => 23,
                'name' => 'Swahili Coast',
                'alternative_names' => null,
                'parent_region_id' => 12,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Kenya', 'Tanzania', 'Mozambique']),
                'historical_names' => $this->textArray(['Azania', 'Zanj']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 24,
                'name' => 'Congo Basin',
                'alternative_names' => null,
                'parent_region_id' => 13,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['DR Congo', 'Republic of Congo', 'Gabon']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 1,
            ],

            // ── Europe: Sub-continental (depth 1) ──────────────────
            [
                'region_id' => 30,
                'name' => 'Mediterranean Europe',
                'alternative_names' => null,
                'parent_region_id' => 3,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Italy', 'Spain', 'Portugal', 'Greece', 'Turkey']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Classical Antiquity', 'Medieval', 'Renaissance']),
                'batch_priority' => 10,
            ],
            [
                'region_id' => 31,
                'name' => 'Western Europe',
                'alternative_names' => null,
                'parent_region_id' => 3,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['France', 'Belgium', 'Netherlands', 'United Kingdom', 'Ireland']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern', 'Modern']),
                'batch_priority' => 8,
            ],
            [
                'region_id' => 32,
                'name' => 'Central Europe',
                'alternative_names' => $this->textArray(['Mitteleuropa']),
                'parent_region_id' => 3,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Germany', 'Austria', 'Switzerland', 'Czech Republic', 'Hungary', 'Poland']),
                'historical_names' => $this->textArray(['Germania', 'Mitteleuropa']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 7,
            ],
            [
                'region_id' => 33,
                'name' => 'Eastern Europe',
                'alternative_names' => null,
                'parent_region_id' => 3,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Russia', 'Ukraine', 'Belarus', 'Romania', 'Bulgaria']),
                'historical_names' => $this->textArray(['Scythia', 'Sarmatia']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 6,
            ],
            [
                'region_id' => 34,
                'name' => 'Scandinavia',
                'alternative_names' => $this->textArray(['Nordic countries']),
                'parent_region_id' => 3,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Norway', 'Sweden', 'Denmark', 'Finland', 'Iceland']),
                'historical_names' => $this->textArray(['Scandia', 'Thule']),
                'typical_periods' => $this->textArray(['Viking Age', 'Medieval']),
                'batch_priority' => 4,
            ],

            // ── Europe: Regional (depth 2) ─────────────────────────
            [
                'region_id' => 35,
                'name' => 'Italian Peninsula',
                'alternative_names' => null,
                'parent_region_id' => 30,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Italy']),
                'historical_names' => $this->textArray(['Italia', 'Magna Graecia (south)']),
                'typical_periods' => $this->textArray(['Classical Antiquity', 'Medieval', 'Renaissance']),
                'batch_priority' => 10,
            ],
            [
                'region_id' => 36,
                'name' => 'Iberian Peninsula',
                'alternative_names' => null,
                'parent_region_id' => 30,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Spain', 'Portugal']),
                'historical_names' => $this->textArray(['Hispania', 'Al-Andalus', 'Iberia']),
                'typical_periods' => $this->textArray(['Roman', 'Medieval Islamic', 'Reconquista']),
                'batch_priority' => 7,
            ],
            [
                'region_id' => 37,
                'name' => 'Greece and Balkans',
                'alternative_names' => null,
                'parent_region_id' => 30,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Greece', 'North Macedonia', 'Serbia', 'Albania', 'Bulgaria', 'Croatia', 'Bosnia']),
                'historical_names' => $this->textArray(['Hellas', 'Thrace', 'Illyria', 'Moesia']),
                'typical_periods' => $this->textArray(['Classical Greece', 'Hellenistic', 'Roman', 'Byzantine', 'Ottoman']),
                'batch_priority' => 9,
            ],
            [
                'region_id' => 38,
                'name' => 'Mediterranean Islands',
                'alternative_names' => null,
                'parent_region_id' => 30,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Cyprus', 'Malta', 'Crete (Greece)', 'Sicily (Italy)', 'Sardinia (Italy)', 'Corsica (France)']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Bronze Age', 'Classical', 'Medieval']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 39,
                'name' => 'France / Gaul',
                'alternative_names' => null,
                'parent_region_id' => 31,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['France']),
                'historical_names' => $this->textArray(['Gallia', 'Gaul', 'Francia']),
                'typical_periods' => $this->textArray(['Iron Age', 'Roman', 'Medieval', 'Early Modern']),
                'batch_priority' => 8,
            ],
            [
                'region_id' => 40,
                'name' => 'Low Countries',
                'alternative_names' => $this->textArray(['Benelux']),
                'parent_region_id' => 31,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Netherlands', 'Belgium', 'Luxembourg']),
                'historical_names' => $this->textArray(['Belgica', 'Flanders', 'Holland']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 41,
                'name' => 'British Isles',
                'alternative_names' => null,
                'parent_region_id' => 31,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['United Kingdom', 'Ireland']),
                'historical_names' => $this->textArray(['Britannia', 'Albion', 'Hibernia']),
                'typical_periods' => $this->textArray(['Roman', 'Anglo-Saxon', 'Medieval', 'Early Modern']),
                'batch_priority' => 7,
            ],
            [
                'region_id' => 42,
                'name' => 'Germanic Lands',
                'alternative_names' => null,
                'parent_region_id' => 32,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Germany', 'Austria', 'Switzerland']),
                'historical_names' => $this->textArray(['Germania', 'Holy Roman Empire']),
                'typical_periods' => $this->textArray(['Roman frontier', 'Medieval', 'Early Modern']),
                'batch_priority' => 7,
            ],
            [
                'region_id' => 43,
                'name' => 'Danubian Region',
                'alternative_names' => null,
                'parent_region_id' => 32,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Hungary', 'Romania', 'Austria', 'Serbia']),
                'historical_names' => $this->textArray(['Pannonia', 'Dacia']),
                'typical_periods' => $this->textArray(['Roman', 'Medieval', 'Ottoman']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 44,
                'name' => 'Slavic Lands',
                'alternative_names' => null,
                'parent_region_id' => 33,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Russia', 'Ukraine', 'Belarus', 'Poland', 'Czech Republic']),
                'historical_names' => $this->textArray(["Rus'", 'Ruthenia']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 6,
            ],
            [
                'region_id' => 45,
                'name' => 'Pontic Steppe',
                'alternative_names' => null,
                'parent_region_id' => 33,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Ukraine', 'Russia', 'Kazakhstan']),
                'historical_names' => $this->textArray(['Scythia', 'Sarmatia', 'Kipchak Steppe']),
                'typical_periods' => $this->textArray(['Bronze Age', 'Iron Age', 'Medieval']),
                'batch_priority' => 4,
            ],
            [
                'region_id' => 46,
                'name' => 'Baltic Region',
                'alternative_names' => null,
                'parent_region_id' => 33,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Lithuania', 'Latvia', 'Estonia']),
                'historical_names' => $this->textArray(['Livonia', 'Courland']),
                'typical_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'batch_priority' => 3,
            ],

            // ── Asia: Sub-continental (depth 1) ────────────────────
            [
                'region_id' => 50,
                'name' => 'Near East / Western Asia',
                'alternative_names' => $this->textArray(['Middle East', 'Western Asia']),
                'parent_region_id' => 4,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Turkey', 'Iraq', 'Syria', 'Iran', 'Israel', 'Lebanon', 'Jordan', 'Saudi Arabia']),
                'historical_names' => $this->textArray(['Orient', 'Mashriq']),
                'typical_periods' => $this->textArray(['Ancient', 'Classical', 'Medieval Islamic']),
                'batch_priority' => 10,
            ],
            [
                'region_id' => 51,
                'name' => 'Central Asia',
                'alternative_names' => $this->textArray(['Inner Asia']),
                'parent_region_id' => 4,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Kazakhstan', 'Uzbekistan', 'Turkmenistan', 'Kyrgyzstan', 'Tajikistan', 'Afghanistan']),
                'historical_names' => $this->textArray(['Turkestan', 'Turan']),
                'typical_periods' => $this->textArray(['Ancient', 'Medieval', 'Mongol']),
                'batch_priority' => 6,
            ],
            [
                'region_id' => 52,
                'name' => 'South Asia',
                'alternative_names' => $this->textArray(['Indian Subcontinent']),
                'parent_region_id' => 4,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal']),
                'historical_names' => $this->textArray(['Hindustan', 'Bharat', 'Jambudvipa']),
                'typical_periods' => $this->textArray(['Indus Valley', 'Vedic', 'Classical', 'Medieval', 'Mughal']),
                'batch_priority' => 8,
            ],
            [
                'region_id' => 53,
                'name' => 'East Asia',
                'alternative_names' => $this->textArray(['Far East']),
                'parent_region_id' => 4,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['China', 'Japan', 'Korea', 'Mongolia', 'Taiwan']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Ancient', 'Imperial', 'Medieval', 'Early Modern']),
                'batch_priority' => 9,
            ],
            [
                'region_id' => 54,
                'name' => 'Southeast Asia',
                'alternative_names' => null,
                'parent_region_id' => 4,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Vietnam', 'Thailand', 'Myanmar', 'Cambodia', 'Indonesia', 'Philippines', 'Malaysia']),
                'historical_names' => $this->textArray(['Indochina', 'Suvarnabhumi']),
                'typical_periods' => $this->textArray(['Classical', 'Medieval', 'Colonial']),
                'batch_priority' => 5,
            ],

            // ── Asia: Regional (depth 2) ───────────────────────────
            [
                'region_id' => 55,
                'name' => 'Mesopotamia',
                'alternative_names' => $this->textArray(['Land between the rivers']),
                'parent_region_id' => 50,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Iraq', 'Syria']),
                'historical_names' => $this->textArray(['Sumer', 'Akkad', 'Babylon', 'Assyria']),
                'typical_periods' => $this->textArray(['Bronze Age', 'Iron Age', 'Classical', 'Islamic']),
                'batch_priority' => 10,
            ],
            [
                'region_id' => 56,
                'name' => 'Levant',
                'alternative_names' => $this->textArray(['Bilad al-Sham']),
                'parent_region_id' => 50,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Syria', 'Lebanon', 'Israel', 'Palestine', 'Jordan']),
                'historical_names' => $this->textArray(['Canaan', 'Palestine', 'Phoenicia', 'Bilad al-Sham']),
                'typical_periods' => $this->textArray(['Bronze Age', 'Iron Age', 'Hellenistic', 'Roman', 'Crusader', 'Islamic']),
                'batch_priority' => 9,
            ],
            [
                'region_id' => 57,
                'name' => 'Anatolia',
                'alternative_names' => $this->textArray(['Asia Minor']),
                'parent_region_id' => 50,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Turkey']),
                'historical_names' => $this->textArray(['Asia Minor', 'Rum']),
                'typical_periods' => $this->textArray(['Bronze Age', 'Classical', 'Byzantine', 'Ottoman']),
                'batch_priority' => 9,
            ],
            [
                'region_id' => 58,
                'name' => 'Arabian Peninsula',
                'alternative_names' => $this->textArray(['Arabia']),
                'parent_region_id' => 50,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Saudi Arabia', 'Yemen', 'Oman', 'UAE', 'Qatar', 'Bahrain', 'Kuwait']),
                'historical_names' => $this->textArray(['Arabia Felix', 'Arabia Deserta', 'Hejaz']),
                'typical_periods' => $this->textArray(['Pre-Islamic', 'Early Islamic', 'Medieval Islamic']),
                'batch_priority' => 7,
            ],
            [
                'region_id' => 59,
                'name' => 'Iranian Plateau',
                'alternative_names' => $this->textArray(['Persia']),
                'parent_region_id' => 50,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Iran', 'Afghanistan']),
                'historical_names' => $this->textArray(['Persia', 'Eranshahr', 'Ariana']),
                'typical_periods' => $this->textArray(['Achaemenid', 'Parthian', 'Sasanian', 'Islamic']),
                'batch_priority' => 8,
            ],
            [
                'region_id' => 60,
                'name' => 'Caucasus',
                'alternative_names' => null,
                'parent_region_id' => 50,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Georgia', 'Armenia', 'Azerbaijan']),
                'historical_names' => $this->textArray(['Colchis', 'Iberia (Caucasian)', 'Albania (Caucasian)']),
                'typical_periods' => $this->textArray(['Classical', 'Medieval', 'Ottoman-Persian frontier']),
                'batch_priority' => 4,
            ],
            [
                'region_id' => 61,
                'name' => 'Transoxiana',
                'alternative_names' => $this->textArray(['Mawarannahr']),
                'parent_region_id' => 51,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Uzbekistan', 'Tajikistan']),
                'historical_names' => $this->textArray(['Mawarannahr', 'Sogdiana', 'Bactria']),
                'typical_periods' => $this->textArray(['Hellenistic', 'Kushan', 'Islamic', 'Timurid']),
                'batch_priority' => 6,
            ],
            [
                'region_id' => 62,
                'name' => 'Steppe Belt',
                'alternative_names' => $this->textArray(['Eurasian Steppe']),
                'parent_region_id' => 51,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Kazakhstan', 'Mongolia', 'Russia']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Bronze Age', 'Turkic', 'Mongol']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 63,
                'name' => 'Tarim Basin',
                'alternative_names' => $this->textArray(['East Turkestan']),
                'parent_region_id' => 51,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['China (Xinjiang)']),
                'historical_names' => $this->textArray(['Western Regions', 'East Turkestan']),
                'typical_periods' => $this->textArray(['Classical', 'Tang', 'Mongol']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 64,
                'name' => 'Indus Valley',
                'alternative_names' => null,
                'parent_region_id' => 52,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Pakistan', 'India']),
                'historical_names' => $this->textArray(['Sindh', 'Sapta Sindhu']),
                'typical_periods' => $this->textArray(['Indus Valley Civilization', 'Vedic', 'Classical']),
                'batch_priority' => 8,
            ],
            [
                'region_id' => 65,
                'name' => 'Gangetic Plain',
                'alternative_names' => null,
                'parent_region_id' => 52,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['India', 'Bangladesh']),
                'historical_names' => $this->textArray(['Aryavarta', 'Madhyadesa']),
                'typical_periods' => $this->textArray(['Vedic', 'Maurya', 'Gupta', 'Mughal']),
                'batch_priority' => 7,
            ],
            [
                'region_id' => 66,
                'name' => 'Deccan',
                'alternative_names' => $this->textArray(['Deccan Plateau']),
                'parent_region_id' => 52,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['India']),
                'historical_names' => $this->textArray(['Dakshinapatha']),
                'typical_periods' => $this->textArray(['Satavahana', 'Chalukya', 'Vijayanagara']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 67,
                'name' => 'Sri Lanka',
                'alternative_names' => $this->textArray(['Ceylon', 'Taprobane']),
                'parent_region_id' => 52,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Sri Lanka']),
                'historical_names' => $this->textArray(['Ceylon', 'Taprobane', 'Lanka']),
                'typical_periods' => $this->textArray(['Classical', 'Medieval', 'Colonial']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 68,
                'name' => 'China - North (Yellow River)',
                'alternative_names' => $this->textArray(['Huang He basin']),
                'parent_region_id' => 53,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['China']),
                'historical_names' => $this->textArray(['Zhongyuan', 'Central Plains']),
                'typical_periods' => $this->textArray(['Shang', 'Zhou', 'Han', 'Tang', 'Song', 'Ming']),
                'batch_priority' => 9,
            ],
            [
                'region_id' => 69,
                'name' => 'China - South (Yangtze)',
                'alternative_names' => $this->textArray(['Changjiang basin']),
                'parent_region_id' => 53,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['China']),
                'historical_names' => $this->textArray(['Jiangnan']),
                'typical_periods' => $this->textArray(['Han', 'Six Dynasties', 'Song', 'Ming']),
                'batch_priority' => 7,
            ],
            [
                'region_id' => 70,
                'name' => 'Korean Peninsula',
                'alternative_names' => null,
                'parent_region_id' => 53,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['South Korea', 'North Korea']),
                'historical_names' => $this->textArray(['Joseon', 'Goryeo', 'Silla']),
                'typical_periods' => $this->textArray(['Three Kingdoms', 'Goryeo', 'Joseon']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 71,
                'name' => 'Japanese Archipelago',
                'alternative_names' => null,
                'parent_region_id' => 53,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Japan']),
                'historical_names' => $this->textArray(['Nihon', 'Yamato', 'Cipangu']),
                'typical_periods' => $this->textArray(['Kofun', 'Nara', 'Heian', 'Kamakura', 'Muromachi', 'Edo']),
                'batch_priority' => 6,
            ],
            [
                'region_id' => 72,
                'name' => 'Mongolian Plateau',
                'alternative_names' => null,
                'parent_region_id' => 53,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Mongolia', 'China (Inner Mongolia)']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Xiongnu', 'Turkic', 'Mongol Empire']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 73,
                'name' => 'Mainland Southeast Asia',
                'alternative_names' => $this->textArray(['Indochina']),
                'parent_region_id' => 54,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Vietnam', 'Thailand', 'Myanmar', 'Cambodia', 'Laos']),
                'historical_names' => $this->textArray(['Indochina', 'Suvarnabhumi']),
                'typical_periods' => $this->textArray(['Khmer', 'Sukhothai', 'Dai Viet']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 74,
                'name' => 'Maritime Southeast Asia',
                'alternative_names' => $this->textArray(['Malay Archipelago', 'Nusantara']),
                'parent_region_id' => 54,
                'depth_level' => 2,
                'modern_countries' => $this->textArray(['Indonesia', 'Philippines', 'Malaysia', 'Brunei', 'Timor-Leste']),
                'historical_names' => $this->textArray(['Nusantara', 'Malay Archipelago']),
                'typical_periods' => $this->textArray(['Srivijaya', 'Majapahit', 'Colonial']),
                'batch_priority' => 4,
            ],

            // ── Americas: Sub-continental (depth 1) ────────────────
            [
                'region_id' => 80,
                'name' => 'North America',
                'alternative_names' => null,
                'parent_region_id' => 5,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['United States', 'Canada', 'Mexico']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Pre-Columbian', 'Colonial', 'Modern']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 81,
                'name' => 'Mesoamerica',
                'alternative_names' => null,
                'parent_region_id' => 5,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Mexico', 'Guatemala', 'Belize', 'Honduras', 'El Salvador']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Preclassic', 'Classic', 'Postclassic']),
                'batch_priority' => 6,
            ],
            [
                'region_id' => 82,
                'name' => 'Caribbean',
                'alternative_names' => $this->textArray(['West Indies']),
                'parent_region_id' => 5,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Cuba', 'Jamaica', 'Haiti', 'Dominican Republic', 'Puerto Rico', 'Trinidad and Tobago']),
                'historical_names' => $this->textArray(['West Indies']),
                'typical_periods' => $this->textArray(['Pre-Columbian', 'Colonial']),
                'batch_priority' => 2,
            ],
            [
                'region_id' => 83,
                'name' => 'Andean Region',
                'alternative_names' => null,
                'parent_region_id' => 5,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Peru', 'Bolivia', 'Ecuador', 'Colombia']),
                'historical_names' => $this->textArray(['Tawantinsuyu']),
                'typical_periods' => $this->textArray(['Pre-Columbian', 'Inca', 'Colonial']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 84,
                'name' => 'Southern Cone',
                'alternative_names' => null,
                'parent_region_id' => 5,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Argentina', 'Chile', 'Uruguay', 'Paraguay']),
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Colonial', 'Modern']),
                'batch_priority' => 1,
            ],

            // ── Oceania: Sub-continental (depth 1) ─────────────────
            [
                'region_id' => 90,
                'name' => 'Australia',
                'alternative_names' => $this->textArray(['Terra Australis']),
                'parent_region_id' => 6,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Australia']),
                'historical_names' => $this->textArray(['Terra Australis', 'New Holland']),
                'typical_periods' => $this->textArray(['Indigenous', 'Colonial']),
                'batch_priority' => 1,
            ],
            [
                'region_id' => 91,
                'name' => 'Melanesia',
                'alternative_names' => null,
                'parent_region_id' => 6,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Papua New Guinea', 'Fiji', 'Solomon Islands', 'Vanuatu']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 1,
            ],
            [
                'region_id' => 92,
                'name' => 'Micronesia',
                'alternative_names' => null,
                'parent_region_id' => 6,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['Federated States of Micronesia', 'Palau', 'Marshall Islands']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 1,
            ],
            [
                'region_id' => 93,
                'name' => 'Polynesia',
                'alternative_names' => null,
                'parent_region_id' => 6,
                'depth_level' => 1,
                'modern_countries' => $this->textArray(['New Zealand', 'Samoa', 'Tonga', 'Hawaii (US)']),
                'historical_names' => null,
                'typical_periods' => null,
                'batch_priority' => 1,
            ],

            // ── Oceans and Maritime Zones: Regional (depth 1) ──────
            [
                'region_id' => 100,
                'name' => 'Mediterranean Sea',
                'alternative_names' => $this->textArray(['Mare Nostrum']),
                'parent_region_id' => 7,
                'depth_level' => 1,
                'modern_countries' => null,
                'historical_names' => $this->textArray(['Mare Nostrum', 'Mare Internum']),
                'typical_periods' => $this->textArray(['Bronze Age', 'Classical', 'Medieval']),
                'batch_priority' => 9,
            ],
            [
                'region_id' => 101,
                'name' => 'Indian Ocean',
                'alternative_names' => null,
                'parent_region_id' => 7,
                'depth_level' => 1,
                'modern_countries' => null,
                'historical_names' => $this->textArray(['Erythraean Sea']),
                'typical_periods' => $this->textArray(['Classical', 'Medieval', 'Age of Exploration']),
                'batch_priority' => 6,
            ],
            [
                'region_id' => 102,
                'name' => 'Atlantic (pre-Columbian)',
                'alternative_names' => null,
                'parent_region_id' => 7,
                'depth_level' => 1,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Age of Exploration', 'Colonial']),
                'batch_priority' => 3,
            ],
            [
                'region_id' => 103,
                'name' => 'Pacific',
                'alternative_names' => null,
                'parent_region_id' => 7,
                'depth_level' => 1,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Austronesian expansion', 'Age of Exploration']),
                'batch_priority' => 2,
            ],
            [
                'region_id' => 104,
                'name' => 'Red Sea',
                'alternative_names' => null,
                'parent_region_id' => 7,
                'depth_level' => 1,
                'modern_countries' => null,
                'historical_names' => $this->textArray(['Erythraean Sea (also)']),
                'typical_periods' => $this->textArray(['Ancient', 'Medieval']),
                'batch_priority' => 4,
            ],
            [
                'region_id' => 105,
                'name' => 'Black Sea',
                'alternative_names' => null,
                'parent_region_id' => 7,
                'depth_level' => 1,
                'modern_countries' => null,
                'historical_names' => $this->textArray(['Pontus Euxinus', 'Pontos']),
                'typical_periods' => $this->textArray(['Greek colonization', 'Byzantine', 'Ottoman']),
                'batch_priority' => 5,
            ],
            [
                'region_id' => 106,
                'name' => 'South China Sea',
                'alternative_names' => null,
                'parent_region_id' => 7,
                'depth_level' => 1,
                'modern_countries' => null,
                'historical_names' => null,
                'typical_periods' => $this->textArray(['Chinese maritime trade', 'Colonial']),
                'batch_priority' => 3,
            ],
        ];
    }
}
