<?php

declare(strict_types=1);

namespace Database\Seeders;

use Database\Seeders\Traits\PgArrayLiteral;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HistoriographicalSchoolSeeder extends Seeder
{
    use PgArrayLiteral;

    public function run(): void
    {
        $table = 'ref_historiographical_schools';

        DB::table($table)->truncate();

        $schools = [
            [
                'school_id' => 1,
                'name' => 'Annales School',
                'alternative_names' => $this->textArray(['Annales historians', 'Annales tradition']),
                'active_from' => '1929',
                'active_to' => null,
                'interpretive_framework' => 'Long-duration structural history (longue durée); social and economic forces over events',
                'methodological_approach' => 'Quantitative methods, serial history, interdisciplinary (geography, economics, anthropology)',
                'evidence_emphasized' => 'Geography, climate, demography, economic structures, price series',
                'evidence_downplayed' => 'Individual agency, political events, diplomatic history',
                'political_commitments' => 'Generally left-leaning but not dogmatically Marxist',
                'geographic_center' => 'France',
                'dominant_regions' => $this->textArray(['Europe', 'Mediterranean']),
                'dominant_periods' => $this->textArray(['Medieval', 'Early Modern']),
                'key_historians' => $this->textArray(['Fernand Braudel', 'Marc Bloch', 'Lucien Febvre', 'Emmanuel Le Roy Ladurie']),
                'foundational_works' => $this->textArray(['The Mediterranean and the Mediterranean World in the Age of Philip II', 'Feudal Society']),
                'influenced_by' => null,
                'opposed_to' => null,
                'sort_order' => 1,
            ],
            [
                'school_id' => 2,
                'name' => 'Marxist Historiography',
                'alternative_names' => $this->textArray(['Historical materialism']),
                'active_from' => '1848',
                'active_to' => null,
                'interpretive_framework' => 'Class struggle and economic base as drivers of historical change',
                'methodological_approach' => 'Dialectical materialism, analysis of modes of production and class relations',
                'evidence_emphasized' => 'Economic relations, labor conditions, class conflict, material conditions',
                'evidence_downplayed' => 'Ideas as independent forces, individual "great men"',
                'political_commitments' => 'Explicitly leftist; views historical process as progressive',
                'geographic_center' => 'Germany, Britain, Soviet Union',
                'dominant_regions' => $this->textArray(['Europe', 'Global']),
                'dominant_periods' => $this->textArray(['Modern', 'Early Modern', 'Medieval']),
                'key_historians' => $this->textArray(['Karl Marx', 'Friedrich Engels', 'E.P. Thompson', 'Eric Hobsbawm', 'Perry Anderson']),
                'foundational_works' => $this->textArray(['The Making of the English Working Class', 'Capital']),
                'influenced_by' => null,
                'opposed_to' => null,
                'sort_order' => 2,
            ],
            [
                'school_id' => 3,
                'name' => 'Postcolonial Studies',
                'alternative_names' => $this->textArray(['Subaltern studies', 'Decolonial history']),
                'active_from' => '1978',
                'active_to' => null,
                'interpretive_framework' => 'Power dynamics of colonialism and its legacies; centering non-Western perspectives',
                'methodological_approach' => 'Reading colonial archives against the grain, recovering subaltern voices',
                'evidence_emphasized' => 'Subaltern voices, colonial archives, oral histories, indigenous sources',
                'evidence_downplayed' => 'Metropolitan perspectives taken at face value',
                'political_commitments' => 'Anti-imperialist; critical of Eurocentric master narratives',
                'geographic_center' => 'South Asia, Africa, Global South',
                'dominant_regions' => $this->textArray(['South Asia', 'Africa', 'Americas', 'Middle East']),
                'dominant_periods' => $this->textArray(['Colonial', 'Modern', 'Contemporary']),
                'key_historians' => $this->textArray(['Edward Said', 'Gayatri Spivak', 'Ranajit Guha', 'Dipesh Chakrabarty', 'Frantz Fanon']),
                'foundational_works' => $this->textArray(['Orientalism', 'Can the Subaltern Speak?', 'Provincializing Europe']),
                'influenced_by' => $this->intArray([2]),
                'opposed_to' => $this->intArray([5]),
                'sort_order' => 3,
            ],
            [
                'school_id' => 4,
                'name' => 'World-Systems Theory',
                'alternative_names' => $this->textArray(['World-systems analysis']),
                'active_from' => '1974',
                'active_to' => null,
                'interpretive_framework' => 'Core-periphery economic relationships determine historical outcomes',
                'methodological_approach' => 'Macro-level analysis of trade flows, resource extraction, labor division',
                'evidence_emphasized' => 'Trade flows, resource extraction, labor division, commodity chains',
                'evidence_downplayed' => 'Cultural factors, local agency, individual decisions',
                'political_commitments' => 'Left-leaning; critical of global capitalism',
                'geographic_center' => 'United States',
                'dominant_regions' => $this->textArray(['Global']),
                'dominant_periods' => $this->textArray(['Early Modern', 'Modern', 'Contemporary']),
                'key_historians' => $this->textArray(['Immanuel Wallerstein', 'Andre Gunder Frank', 'Giovanni Arrighi']),
                'foundational_works' => $this->textArray(['The Modern World-System']),
                'influenced_by' => $this->intArray([1, 2]),
                'opposed_to' => null,
                'sort_order' => 4,
            ],
            [
                'school_id' => 5,
                'name' => 'Rankean Empiricism',
                'alternative_names' => $this->textArray(['Scientific history', 'Source-critical method']),
                'active_from' => '1824',
                'active_to' => null,
                'interpretive_framework' => '"How it actually happened" (wie es eigentlich gewesen) — rigorous primary source criticism',
                'methodological_approach' => 'Archival research, source criticism, diplomatic history',
                'evidence_emphasized' => 'Official documents, diplomatic archives, state records',
                'evidence_downplayed' => 'Popular culture, non-elite perspectives, oral tradition',
                'political_commitments' => 'Claims objectivity; often conservative-nationalist in practice',
                'geographic_center' => 'Germany',
                'dominant_regions' => $this->textArray(['Europe']),
                'dominant_periods' => $this->textArray(['Early Modern', 'Modern']),
                'key_historians' => $this->textArray(['Leopold von Ranke']),
                'foundational_works' => $this->textArray(['History of the Latin and Teutonic Peoples']),
                'influenced_by' => null,
                'opposed_to' => null,
                'sort_order' => 5,
            ],
            [
                'school_id' => 6,
                'name' => 'Cultural / Intellectual History',
                'alternative_names' => $this->textArray(['History of ideas', 'History of mentalities']),
                'active_from' => '1920',
                'active_to' => null,
                'interpretive_framework' => 'Ideas, mentalities, and meaning-making as drivers of historical change',
                'methodological_approach' => 'Textual analysis, discourse analysis, contextual reading of ideas',
                'evidence_emphasized' => 'Texts, art, symbols, discourse, intellectual correspondence',
                'evidence_downplayed' => 'Material conditions (unless culturally mediated)',
                'political_commitments' => 'Varies; generally liberal-humanist',
                'geographic_center' => 'Britain, United States',
                'dominant_regions' => $this->textArray(['Europe', 'Global']),
                'dominant_periods' => $this->textArray(['Early Modern', 'Modern']),
                'key_historians' => $this->textArray(['Arthur Lovejoy', 'Quentin Skinner', 'Roger Chartier', 'Robert Darnton']),
                'foundational_works' => $this->textArray(['The Great Chain of Being', 'The Cat Massacre']),
                'influenced_by' => null,
                'opposed_to' => null,
                'sort_order' => 6,
            ],
            [
                'school_id' => 7,
                'name' => 'Environmental History',
                'alternative_names' => $this->textArray(['Ecological history']),
                'active_from' => '1970',
                'active_to' => null,
                'interpretive_framework' => 'Human-environment interaction over time; nature as historical actor',
                'methodological_approach' => 'Interdisciplinary (ecology, geology, climatology), long-duration analysis',
                'evidence_emphasized' => 'Climate data, ecology, disease, agricultural records, pollen cores',
                'evidence_downplayed' => 'Purely political narratives that ignore environmental context',
                'political_commitments' => 'Often aligned with environmentalism',
                'geographic_center' => 'United States',
                'dominant_regions' => $this->textArray(['Global']),
                'dominant_periods' => $this->textArray(['All periods']),
                'key_historians' => $this->textArray(['Alfred Crosby', 'William Cronon', 'John McNeill', 'Kyle Harper']),
                'foundational_works' => $this->textArray(['The Columbian Exchange', 'Changes in the Land', 'The Fate of Rome']),
                'influenced_by' => $this->intArray([1]),
                'opposed_to' => null,
                'sort_order' => 7,
            ],
            [
                'school_id' => 8,
                'name' => 'Cliometrics / New Economic History',
                'alternative_names' => $this->textArray(['Cliometrics', 'Econometric history']),
                'active_from' => '1957',
                'active_to' => null,
                'interpretive_framework' => 'Quantitative analysis of economic history using statistical methods',
                'methodological_approach' => 'Econometric models, counterfactual analysis, statistical data',
                'evidence_emphasized' => 'Statistical data, price series, trade records, GDP estimates',
                'evidence_downplayed' => 'Qualitative sources, cultural context, individual experience',
                'political_commitments' => 'Claims value-neutrality; often aligned with neoclassical economics',
                'geographic_center' => 'United States',
                'dominant_regions' => $this->textArray(['Europe', 'Americas']),
                'dominant_periods' => $this->textArray(['Modern', 'Early Modern']),
                'key_historians' => $this->textArray(['Robert Fogel', 'Douglass North', 'Angus Maddison']),
                'foundational_works' => $this->textArray(['Time on the Cross', 'The Rise of the Western World']),
                'influenced_by' => null,
                'opposed_to' => null,
                'sort_order' => 8,
            ],
            [
                'school_id' => 9,
                'name' => 'Gender History',
                'alternative_names' => $this->textArray(["Women's history", 'Feminist historiography']),
                'active_from' => '1970',
                'active_to' => null,
                'interpretive_framework' => 'Gender as a fundamental category of historical analysis',
                'methodological_approach' => 'Feminist theory applied to historical research, intersectionality',
                'evidence_emphasized' => "Women's experiences, masculinity studies, sexuality, family structure",
                'evidence_downplayed' => 'Purely political/military narratives that ignore gender',
                'political_commitments' => 'Feminist; questions patriarchal assumptions in historical narratives',
                'geographic_center' => 'United States, Britain',
                'dominant_regions' => $this->textArray(['Global']),
                'dominant_periods' => $this->textArray(['All periods']),
                'key_historians' => $this->textArray(['Joan Wallach Scott', 'Natalie Zemon Davis', 'Judith Bennett']),
                'foundational_works' => $this->textArray(['Gender and the Politics of History']),
                'influenced_by' => $this->intArray([3]),
                'opposed_to' => null,
                'sort_order' => 9,
            ],
            [
                'school_id' => 10,
                'name' => 'Big History',
                'alternative_names' => $this->textArray(['Deep history', 'Universal history']),
                'active_from' => '1989',
                'active_to' => null,
                'interpretive_framework' => 'Very long timescales including pre-human; thresholds of complexity',
                'methodological_approach' => 'Interdisciplinary synthesis (cosmology, geology, biology, history)',
                'evidence_emphasized' => 'Archaeological, geological, astronomical, biological evidence',
                'evidence_downplayed' => 'Detailed political narrative (too zoomed out)',
                'political_commitments' => 'Generally universalist; seeks common human story',
                'geographic_center' => 'United States, Australia',
                'dominant_regions' => $this->textArray(['Global']),
                'dominant_periods' => $this->textArray(['All periods including pre-human']),
                'key_historians' => $this->textArray(['David Christian', 'Fred Spier']),
                'foundational_works' => $this->textArray(['Maps of Time']),
                'influenced_by' => $this->intArray([1, 7]),
                'opposed_to' => null,
                'sort_order' => 10,
            ],
            [
                'school_id' => 11,
                'name' => 'Military History (New)',
                'alternative_names' => $this->textArray(['New military history', 'War and society']),
                'active_from' => '1970',
                'active_to' => null,
                'interpretive_framework' => 'War in social, cultural, and economic context — beyond battles and generals',
                'methodological_approach' => "Social history of warfare, soldiers' experiences, home front analysis",
                'evidence_emphasized' => "Soldiers' letters, logistics records, home front sources, archaeological battlefields",
                'evidence_downplayed' => 'Pure operational narrative without social context',
                'political_commitments' => 'Varies; often critical of glorifying war',
                'geographic_center' => 'Britain, United States',
                'dominant_regions' => $this->textArray(['Global']),
                'dominant_periods' => $this->textArray(['All periods']),
                'key_historians' => $this->textArray(['John Keegan', 'Victor Davis Hanson', 'Jeremy Black']),
                'foundational_works' => $this->textArray(['The Face of Battle']),
                'influenced_by' => $this->intArray([1]),
                'opposed_to' => null,
                'sort_order' => 11,
            ],
            [
                'school_id' => 12,
                'name' => 'Microhistory',
                'alternative_names' => $this->textArray(['Microstoria']),
                'active_from' => '1976',
                'active_to' => null,
                'interpretive_framework' => 'Intensive study of small units (village, trial, individual) to reveal large patterns',
                'methodological_approach' => 'Close reading of local archives, thick description, narrative technique',
                'evidence_emphasized' => 'Local archives, court records, personal papers, inquisition records',
                'evidence_downplayed' => 'Grand narrative and macro-level generalization',
                'political_commitments' => 'Sympathetic to ordinary people; often left-leaning',
                'geographic_center' => 'Italy',
                'dominant_regions' => $this->textArray(['Europe']),
                'dominant_periods' => $this->textArray(['Early Modern', 'Medieval']),
                'key_historians' => $this->textArray(['Carlo Ginzburg', 'Giovanni Levi', 'Natalie Zemon Davis', 'Emmanuel Le Roy Ladurie']),
                'foundational_works' => $this->textArray(['The Cheese and the Worms', 'Montaillou', 'The Return of Martin Guerre']),
                'influenced_by' => $this->intArray([1]),
                'opposed_to' => null,
                'sort_order' => 12,
            ],
        ];

        foreach ($schools as $school) {
            DB::table($table)->insert($school);
        }
    }
}
