<?php

declare(strict_types=1);

namespace Database\Seeders;

use Database\Seeders\Traits\PgArrayLiteral;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HistoricalPeriodSeeder extends Seeder
{
    use PgArrayLiteral;

    public function run(): void
    {
        $table = 'ref_historical_periods';

        DB::statement('ALTER TABLE ref_historical_periods DISABLE TRIGGER ALL');
        DB::table($table)->truncate();

        $periods = $this->buildPeriodTree();
        $sort = 0;

        foreach ($periods as $period) {
            $period['sort_order'] = ++$sort;
            DB::table($table)->insert($period);
        }

        DB::statement('ALTER TABLE ref_historical_periods ENABLE TRIGGER ALL');
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function buildPeriodTree(): array
    {
        return [
            // ══════════════════════════════════════════════
            // WESTERN CONVENTIONAL
            // ══════════════════════════════════════════════

            // Depth 0: Ancient
            [
                'period_id' => 1,
                'name' => 'Ancient',
                'alternative_names' => $this->textArray(['Antiquity']),
                'start_date' => '-3000000',
                'end_date' => '500',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Emergence and development of civilizations from earliest humans to the fall of Rome',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Fall of Rome (476 CE)',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#8B4513',
            ],

            // Depth 1: Prehistoric
            [
                'period_id' => 2,
                'name' => 'Prehistoric',
                'alternative_names' => $this->textArray(['Pre-literate period']),
                'start_date' => '-3000000',
                'end_date' => '-3300',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 1,
                'depth_level' => 1,
                'defining_characteristics' => 'Human development before writing systems',
                'conventional_start_event' => 'Emergence of Homo habilis',
                'conventional_end_event' => 'Emergence of writing in Mesopotamia',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#A0522D',
            ],

            // Depth 2: Paleolithic
            [
                'period_id' => 3,
                'name' => 'Paleolithic',
                'alternative_names' => $this->textArray(['Old Stone Age']),
                'start_date' => '-3000000',
                'end_date' => '-10000',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 2,
                'depth_level' => 2,
                'defining_characteristics' => 'Stone tool use, hunter-gatherer societies',
                'conventional_start_event' => null,
                'conventional_end_event' => 'End of last Ice Age',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#654321',
            ],

            // Depth 2: Mesolithic
            [
                'period_id' => 4,
                'name' => 'Mesolithic',
                'alternative_names' => $this->textArray(['Middle Stone Age']),
                'start_date' => '-10000',
                'end_date' => '-8000',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 2,
                'depth_level' => 2,
                'defining_characteristics' => 'Transitional period between Paleolithic and Neolithic',
                'conventional_start_event' => 'End of last Ice Age',
                'conventional_end_event' => 'Onset of agriculture',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#8B7355',
            ],

            // Depth 2: Neolithic
            [
                'period_id' => 5,
                'name' => 'Neolithic',
                'alternative_names' => $this->textArray(['New Stone Age', 'Agricultural Revolution']),
                'start_date' => '-8000',
                'end_date' => '-3300',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 2,
                'depth_level' => 2,
                'defining_characteristics' => 'Development of agriculture, permanent settlements, pottery',
                'conventional_start_event' => 'Onset of agriculture in Fertile Crescent',
                'conventional_end_event' => 'Emergence of bronze working',
                'historiographical_notes' => 'Regional variation is enormous; dates are for Near East',
                'value_judgments' => null,
                'color_hex' => '#CD853F',
            ],

            // Depth 1: Bronze Age
            [
                'period_id' => 6,
                'name' => 'Bronze Age',
                'alternative_names' => null,
                'start_date' => '-3300',
                'end_date' => '-1200',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Eastern Mediterranean',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 1,
                'depth_level' => 1,
                'defining_characteristics' => 'Bronze metallurgy, early writing systems, first empires',
                'conventional_start_event' => 'Development of bronze alloys',
                'conventional_end_event' => 'Bronze Age Collapse',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#CD7F32',
            ],
            [
                'period_id' => 7,
                'name' => 'Early Bronze Age',
                'alternative_names' => $this->textArray(['EBA']),
                'start_date' => '-3300',
                'end_date' => '-2000',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Eastern Mediterranean',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 6,
                'depth_level' => 2,
                'defining_characteristics' => 'Rise of Sumerian civilization, Old Kingdom Egypt',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#B8860B',
            ],
            [
                'period_id' => 8,
                'name' => 'Middle Bronze Age',
                'alternative_names' => $this->textArray(['MBA']),
                'start_date' => '-2000',
                'end_date' => '-1600',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Eastern Mediterranean',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 6,
                'depth_level' => 2,
                'defining_characteristics' => 'Rise of Babylon, Minoan civilization peak',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#DAA520',
            ],
            [
                'period_id' => 9,
                'name' => 'Late Bronze Age',
                'alternative_names' => $this->textArray(['LBA']),
                'start_date' => '-1600',
                'end_date' => '-1200',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Eastern Mediterranean',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 6,
                'depth_level' => 2,
                'defining_characteristics' => 'International system of great powers; ended by collapse',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Sea Peoples invasions, collapse of palatial centers',
                'historiographical_notes' => 'Exact causes of collapse remain hotly debated',
                'value_judgments' => null,
                'color_hex' => '#FFD700',
            ],

            // Depth 1: Iron Age
            [
                'period_id' => 10,
                'name' => 'Iron Age',
                'alternative_names' => null,
                'start_date' => '-1200',
                'end_date' => '-500',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Mediterranean and Near East',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 1,
                'depth_level' => 1,
                'defining_characteristics' => 'Iron metallurgy, alphabetic writing, rise of new empires',
                'conventional_start_event' => 'Bronze Age Collapse',
                'conventional_end_event' => 'Rise of Classical Greece and Achaemenid Persia',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#708090',
            ],

            // Depth 1: Classical Antiquity
            [
                'period_id' => 11,
                'name' => 'Classical Antiquity',
                'alternative_names' => $this->textArray(['Classical Period', 'Greco-Roman world']),
                'start_date' => '-500',
                'end_date' => '500',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Mediterranean',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 1,
                'depth_level' => 1,
                'defining_characteristics' => 'Greek and Roman civilization at its height',
                'conventional_start_event' => 'Rise of Athenian democracy, Persian Wars',
                'conventional_end_event' => 'Fall of Western Roman Empire',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#4169E1',
            ],

            // Depth 2: Greek periods
            [
                'period_id' => 12,
                'name' => 'Archaic Greece',
                'alternative_names' => $this->textArray(['Greek Archaic Period']),
                'start_date' => '-800',
                'end_date' => '-480',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Greece and Aegean',
                'region_id' => 37,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 11,
                'depth_level' => 2,
                'defining_characteristics' => 'Polis formation, colonization, rise of hoplite warfare',
                'conventional_start_event' => 'Emergence of Greek city-states',
                'conventional_end_event' => 'Persian Wars begin',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#6495ED',
            ],
            [
                'period_id' => 13,
                'name' => 'Classical Greece',
                'alternative_names' => $this->textArray(['Golden Age of Athens']),
                'start_date' => '-480',
                'end_date' => '-323',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Greece',
                'region_id' => 37,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 11,
                'depth_level' => 2,
                'defining_characteristics' => 'Athenian democracy, philosophy, drama, Peloponnesian War',
                'conventional_start_event' => 'Battle of Salamis (480 BCE)',
                'conventional_end_event' => 'Death of Alexander the Great',
                'historiographical_notes' => null,
                'value_judgments' => '"Golden Age" implies a value judgment; period also includes devastating warfare',
                'color_hex' => '#4682B4',
            ],
            [
                'period_id' => 14,
                'name' => 'Hellenistic Period',
                'alternative_names' => $this->textArray(['Hellenistic Age']),
                'start_date' => '-323',
                'end_date' => '-31',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Mediterranean and Near East',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 11,
                'depth_level' => 2,
                'defining_characteristics' => 'Successor kingdoms, cultural diffusion, scientific advances',
                'conventional_start_event' => 'Death of Alexander the Great',
                'conventional_end_event' => 'Battle of Actium (31 BCE)',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#5F9EA0',
            ],

            // Depth 2: Roman periods
            [
                'period_id' => 15,
                'name' => 'Roman Republic',
                'alternative_names' => $this->textArray(['Republican Rome']),
                'start_date' => '-509',
                'end_date' => '-27',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Mediterranean',
                'region_id' => 35,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 11,
                'depth_level' => 2,
                'defining_characteristics' => 'Republican government, territorial expansion, civil wars',
                'conventional_start_event' => 'Overthrow of Roman monarchy',
                'conventional_end_event' => 'Augustus becomes princeps',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#B22222',
            ],
            [
                'period_id' => 16,
                'name' => 'Early Republic',
                'alternative_names' => null,
                'start_date' => '-509',
                'end_date' => '-264',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Italian Peninsula',
                'region_id' => 35,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 15,
                'depth_level' => 3,
                'defining_characteristics' => 'Struggle of the Orders, conquest of Italy',
                'conventional_start_event' => 'Overthrow of Tarquinius Superbus',
                'conventional_end_event' => 'First Punic War begins',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#CD5C5C',
            ],
            [
                'period_id' => 17,
                'name' => 'Middle Republic',
                'alternative_names' => null,
                'start_date' => '-264',
                'end_date' => '-133',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Mediterranean',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 15,
                'depth_level' => 3,
                'defining_characteristics' => 'Punic Wars, Mediterranean hegemony',
                'conventional_start_event' => 'First Punic War',
                'conventional_end_event' => 'Tribunate of Tiberius Gracchus',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#DC143C',
            ],
            [
                'period_id' => 18,
                'name' => 'Late Republic',
                'alternative_names' => null,
                'start_date' => '-133',
                'end_date' => '-27',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Mediterranean',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 15,
                'depth_level' => 3,
                'defining_characteristics' => 'Civil wars, political violence, collapse of republican institutions',
                'conventional_start_event' => 'Tribunate of Tiberius Gracchus',
                'conventional_end_event' => 'Battle of Actium',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#FF0000',
            ],
            [
                'period_id' => 19,
                'name' => 'Roman Empire',
                'alternative_names' => $this->textArray(['Imperial Rome']),
                'start_date' => '-27',
                'end_date' => '476',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Mediterranean and Europe',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 11,
                'depth_level' => 2,
                'defining_characteristics' => 'Imperial government, Pax Romana, territorial peak, decline',
                'conventional_start_event' => 'Augustus becomes princeps',
                'conventional_end_event' => 'Deposition of Romulus Augustulus',
                'historiographical_notes' => 'Eastern Empire continues as Byzantine until 1453',
                'value_judgments' => null,
                'color_hex' => '#8B0000',
            ],
            [
                'period_id' => 20,
                'name' => 'Principate',
                'alternative_names' => null,
                'start_date' => '-27',
                'end_date' => '284',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Roman Empire',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 19,
                'depth_level' => 3,
                'defining_characteristics' => 'Augustus to Diocletian; emperor as first citizen',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Accession of Diocletian',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#A52A2A',
            ],
            [
                'period_id' => 21,
                'name' => 'Crisis of the Third Century',
                'alternative_names' => $this->textArray(['Military Anarchy', 'Imperial Crisis']),
                'start_date' => '235',
                'end_date' => '284',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Roman Empire',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 19,
                'depth_level' => 3,
                'defining_characteristics' => 'Military coups, breakaway empires, plague, economic collapse',
                'conventional_start_event' => 'Assassination of Severus Alexander',
                'conventional_end_event' => 'Accession of Diocletian',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#800000',
            ],
            [
                'period_id' => 22,
                'name' => 'Dominate',
                'alternative_names' => $this->textArray(['Late Roman Empire']),
                'start_date' => '284',
                'end_date' => '476',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Roman Empire',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 19,
                'depth_level' => 3,
                'defining_characteristics' => 'Diocletian reforms, Christianization, division, western collapse',
                'conventional_start_event' => 'Accession of Diocletian',
                'conventional_end_event' => 'Deposition of Romulus Augustulus',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#660000',
            ],
            [
                'period_id' => 23,
                'name' => 'Tetrarchy',
                'alternative_names' => null,
                'start_date' => '293',
                'end_date' => '313',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Roman Empire',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 19,
                'depth_level' => 3,
                'defining_characteristics' => 'Four-emperor system of government',
                'conventional_start_event' => 'Diocletian appoints Maximian, Galerius, and Constantius',
                'conventional_end_event' => 'Edict of Milan',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#4A0000',
            ],
            [
                'period_id' => 24,
                'name' => 'Late Antiquity',
                'alternative_names' => null,
                'start_date' => '284',
                'end_date' => '700',
                'date_precision' => 'debated',
                'geographic_scope' => 'Mediterranean',
                'region_id' => 100,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 11,
                'depth_level' => 2,
                'defining_characteristics' => 'Transition from classical to medieval; Christianization, Germanic migrations',
                'conventional_start_event' => 'Accession of Diocletian (or earlier)',
                'conventional_end_event' => 'Arab conquests / Rise of Islam',
                'historiographical_notes' => 'Boundary dates are highly debated; Peter Brown popularized the concept',
                'value_judgments' => 'Replaces older "Dark Ages" label which implied cultural decline',
                'color_hex' => '#556B2F',
            ],

            // ── Medieval ──────────────────────────────────
            [
                'period_id' => 30,
                'name' => 'Medieval',
                'alternative_names' => $this->textArray(['Middle Ages']),
                'start_date' => '500',
                'end_date' => '1500',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Europe',
                'region_id' => 3,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Feudalism, Christendom, manorial economy, crusades',
                'conventional_start_event' => 'Fall of Western Roman Empire',
                'conventional_end_event' => 'Fall of Constantinople / Columbus',
                'historiographical_notes' => 'Primarily a European periodization; less useful for other regions',
                'value_judgments' => '"Dark Ages" is considered pejorative and inaccurate',
                'color_hex' => '#2F4F4F',
            ],
            [
                'period_id' => 31,
                'name' => 'Early Medieval',
                'alternative_names' => $this->textArray(['Early Middle Ages']),
                'start_date' => '500',
                'end_date' => '1000',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Europe',
                'region_id' => 3,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 30,
                'depth_level' => 1,
                'defining_characteristics' => 'Germanic kingdoms, Carolingian Empire, Viking Age, Byzantine resilience',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#3B5323',
            ],
            [
                'period_id' => 32,
                'name' => 'High Medieval',
                'alternative_names' => $this->textArray(['High Middle Ages']),
                'start_date' => '1000',
                'end_date' => '1300',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Europe',
                'region_id' => 3,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 30,
                'depth_level' => 1,
                'defining_characteristics' => 'Crusades, cathedral building, scholasticism, population growth',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#006400',
            ],
            [
                'period_id' => 33,
                'name' => 'Late Medieval',
                'alternative_names' => $this->textArray(['Late Middle Ages']),
                'start_date' => '1300',
                'end_date' => '1500',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Europe',
                'region_id' => 3,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 30,
                'depth_level' => 1,
                'defining_characteristics' => 'Black Death, Hundred Years War, decline of feudalism',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#228B22',
            ],

            // ── Early Modern ──────────────────────────────
            [
                'period_id' => 34,
                'name' => 'Early Modern',
                'alternative_names' => $this->textArray(['Early Modern Period']),
                'start_date' => '1500',
                'end_date' => '1800',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Renaissance, Reformation, Age of Exploration, Scientific Revolution, Enlightenment',
                'conventional_start_event' => 'Fall of Constantinople / Columbus',
                'conventional_end_event' => 'French Revolution',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#B8860B',
            ],

            // ── Modern ────────────────────────────────────
            [
                'period_id' => 35,
                'name' => 'Modern',
                'alternative_names' => $this->textArray(['Modern Period']),
                'start_date' => '1800',
                'end_date' => '2026',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Industrialization, nationalism, imperialism, world wars, decolonization',
                'conventional_start_event' => 'French Revolution / Napoleonic Wars',
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#4682B4',
            ],
            [
                'period_id' => 36,
                'name' => 'Long 19th Century',
                'alternative_names' => null,
                'start_date' => '1789',
                'end_date' => '1914',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 35,
                'depth_level' => 1,
                'defining_characteristics' => 'Revolutions, industrialization, imperialism, nationalism',
                'conventional_start_event' => 'French Revolution',
                'conventional_end_event' => 'World War I begins',
                'historiographical_notes' => 'Eric Hobsbawm concept',
                'value_judgments' => null,
                'color_hex' => '#5B9BD5',
            ],
            [
                'period_id' => 37,
                'name' => 'World Wars',
                'alternative_names' => $this->textArray(['Age of Catastrophe']),
                'start_date' => '1914',
                'end_date' => '1945',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 35,
                'depth_level' => 1,
                'defining_characteristics' => 'Two world wars, totalitarianism, genocide, nuclear weapons',
                'conventional_start_event' => 'Assassination of Archduke Franz Ferdinand',
                'conventional_end_event' => 'Surrender of Japan',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#C0392B',
            ],
            [
                'period_id' => 38,
                'name' => 'Contemporary',
                'alternative_names' => $this->textArray(['Post-war period', 'Cold War era and after']),
                'start_date' => '1945',
                'end_date' => '2026',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Global',
                'region_id' => null,
                'periodization_scheme' => 'Western conventional',
                'parent_period_id' => 35,
                'depth_level' => 1,
                'defining_characteristics' => 'Cold War, decolonization, globalization, digital revolution',
                'conventional_start_event' => 'End of World War II',
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#2E86C1',
            ],

            // ══════════════════════════════════════════════
            // CHINESE DYNASTIC
            // ══════════════════════════════════════════════
            [
                'period_id' => 50,
                'name' => 'Xia Dynasty',
                'alternative_names' => null,
                'start_date' => '-2070',
                'end_date' => '-1600',
                'date_precision' => 'debated',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Traditionally first dynasty; historicity debated',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => 'Archaeological evidence is debated; some scholars treat as legendary',
                'value_judgments' => null,
                'color_hex' => '#8B4513',
            ],
            [
                'period_id' => 51,
                'name' => 'Shang Dynasty',
                'alternative_names' => $this->textArray(['Yin Dynasty']),
                'start_date' => '-1600',
                'end_date' => '-1046',
                'date_precision' => 'approximate',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'First dynasty with archaeological evidence, oracle bones, bronze casting',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Battle of Muye',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#CD7F32',
            ],
            [
                'period_id' => 52,
                'name' => 'Zhou Dynasty',
                'alternative_names' => null,
                'start_date' => '-1046',
                'end_date' => '-256',
                'date_precision' => 'approximate',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Mandate of Heaven, feudal system, Confucius, Laozi',
                'conventional_start_event' => 'Battle of Muye',
                'conventional_end_event' => 'Conquest by Qin',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#DAA520',
            ],
            [
                'period_id' => 53,
                'name' => 'Western Zhou',
                'alternative_names' => null,
                'start_date' => '-1046',
                'end_date' => '-771',
                'date_precision' => 'approximate',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => 52,
                'depth_level' => 1,
                'defining_characteristics' => 'Feudal system, bronze ritual vessels, early written records',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Sack of Haojing',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#B8860B',
            ],
            [
                'period_id' => 54,
                'name' => 'Eastern Zhou',
                'alternative_names' => null,
                'start_date' => '-771',
                'end_date' => '-256',
                'date_precision' => 'approximate',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => 52,
                'depth_level' => 1,
                'defining_characteristics' => 'Decline of royal authority, rise of powerful states',
                'conventional_start_event' => 'Move to Luoyang',
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#CD853F',
            ],
            [
                'period_id' => 55,
                'name' => 'Spring and Autumn',
                'alternative_names' => $this->textArray(['Chunqiu']),
                'start_date' => '-771',
                'end_date' => '-476',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => 54,
                'depth_level' => 2,
                'defining_characteristics' => 'Hegemonic system, Confucius, philosophical flourishing',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#8B7355',
            ],
            [
                'period_id' => 56,
                'name' => 'Warring States',
                'alternative_names' => $this->textArray(['Zhanguo']),
                'start_date' => '-476',
                'end_date' => '-221',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => 54,
                'depth_level' => 2,
                'defining_characteristics' => 'Seven major states competing, mass warfare, Legalism',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Qin unification',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#A0522D',
            ],
            [
                'period_id' => 57,
                'name' => 'Qin Dynasty',
                'alternative_names' => null,
                'start_date' => '-221',
                'end_date' => '-206',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'First unified empire, standardization, Great Wall, Terracotta Army',
                'conventional_start_event' => 'Qin Shi Huang unifies China',
                'conventional_end_event' => 'Collapse after Shi Huang\'s death',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#708090',
            ],
            [
                'period_id' => 58,
                'name' => 'Han Dynasty',
                'alternative_names' => null,
                'start_date' => '-206',
                'end_date' => '220',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Confucian state ideology, Silk Road, paper invention, territorial expansion',
                'conventional_start_event' => 'Liu Bang founds Han',
                'conventional_end_event' => 'Abdication of Emperor Xian',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#C0392B',
            ],
            [
                'period_id' => 59,
                'name' => 'Western Han',
                'alternative_names' => $this->textArray(['Former Han']),
                'start_date' => '-206',
                'end_date' => '9',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => 58,
                'depth_level' => 1,
                'defining_characteristics' => null,
                'conventional_start_event' => null,
                'conventional_end_event' => 'Wang Mang usurpation',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#E74C3C',
            ],
            [
                'period_id' => 60,
                'name' => 'Xin Dynasty',
                'alternative_names' => null,
                'start_date' => '9',
                'end_date' => '23',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => 58,
                'depth_level' => 1,
                'defining_characteristics' => 'Wang Mang interregnum, radical land and currency reforms',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#D35400',
            ],
            [
                'period_id' => 61,
                'name' => 'Eastern Han',
                'alternative_names' => $this->textArray(['Later Han']),
                'start_date' => '25',
                'end_date' => '220',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => 58,
                'depth_level' => 1,
                'defining_characteristics' => 'Restoration, Buddhism arrives, eunuch factionalism',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#CB4335',
            ],
            [
                'period_id' => 62,
                'name' => 'Three Kingdoms',
                'alternative_names' => $this->textArray(['Sanguo']),
                'start_date' => '220',
                'end_date' => '280',
                'date_precision' => 'conventional',
                'geographic_scope' => 'China',
                'region_id' => 68,
                'periodization_scheme' => 'Chinese dynastic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Wei, Shu, Wu; romanticized in literature',
                'conventional_start_event' => 'Abdication of Han Emperor Xian',
                'conventional_end_event' => 'Jin unification',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#8E44AD',
            ],

            // ══════════════════════════════════════════════
            // ISLAMIC
            // ══════════════════════════════════════════════
            [
                'period_id' => 70,
                'name' => 'Prophetic Period',
                'alternative_names' => $this->textArray(['Era of the Prophet']),
                'start_date' => '610',
                'end_date' => '632',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Arabian Peninsula',
                'region_id' => 58,
                'periodization_scheme' => 'Islamic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Muhammad receives revelation, Hijra, founding of Islamic community',
                'conventional_start_event' => 'First revelation',
                'conventional_end_event' => 'Death of Muhammad',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#27AE60',
            ],
            [
                'period_id' => 71,
                'name' => 'Rashidun Caliphate',
                'alternative_names' => $this->textArray(['Rightly Guided Caliphs']),
                'start_date' => '632',
                'end_date' => '661',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Middle East and North Africa',
                'region_id' => 50,
                'periodization_scheme' => 'Islamic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Rapid conquests, compilation of Quran, fitna (civil wars)',
                'conventional_start_event' => 'Abu Bakr becomes caliph',
                'conventional_end_event' => 'Assassination of Ali',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#2ECC71',
            ],
            [
                'period_id' => 72,
                'name' => 'Umayyad Caliphate',
                'alternative_names' => null,
                'start_date' => '661',
                'end_date' => '750',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Middle East, North Africa, Iberia',
                'region_id' => 50,
                'periodization_scheme' => 'Islamic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Largest contiguous caliphate, Arabization, Dome of the Rock',
                'conventional_start_event' => 'Muawiya becomes caliph',
                'conventional_end_event' => 'Abbasid Revolution',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#1ABC9C',
            ],
            [
                'period_id' => 73,
                'name' => 'Abbasid Caliphate',
                'alternative_names' => null,
                'start_date' => '750',
                'end_date' => '1258',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Islamic world',
                'region_id' => 50,
                'periodization_scheme' => 'Islamic',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Islamic Golden Age, Baghdad as center, translation movement',
                'conventional_start_event' => 'Abbasid Revolution',
                'conventional_end_event' => 'Mongol sack of Baghdad',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#16A085',
            ],
            [
                'period_id' => 74,
                'name' => 'Early Abbasid Golden Age',
                'alternative_names' => $this->textArray(['Islamic Golden Age']),
                'start_date' => '750',
                'end_date' => '847',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Islamic world',
                'region_id' => 50,
                'periodization_scheme' => 'Islamic',
                'parent_period_id' => 73,
                'depth_level' => 1,
                'defining_characteristics' => 'House of Wisdom, scientific and philosophical florescence',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Death of al-Mutawakkil, Turkish military dominance begins',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#148F77',
            ],
            [
                'period_id' => 75,
                'name' => 'Late Abbasid / Fragmentation',
                'alternative_names' => null,
                'start_date' => '847',
                'end_date' => '1258',
                'date_precision' => 'conventional',
                'geographic_scope' => 'Islamic world',
                'region_id' => 50,
                'periodization_scheme' => 'Islamic',
                'parent_period_id' => 73,
                'depth_level' => 1,
                'defining_characteristics' => 'Caliphal decline, autonomous dynasties, Crusades, Seljuk and Mongol invasions',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Mongol sack of Baghdad',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#117A65',
            ],

            // ══════════════════════════════════════════════
            // SOUTH ASIAN
            // ══════════════════════════════════════════════
            [
                'period_id' => 80,
                'name' => 'Indus Valley Civilization',
                'alternative_names' => $this->textArray(['Harappan Civilization']),
                'start_date' => '-3300',
                'end_date' => '-1300',
                'date_precision' => 'approximate',
                'geographic_scope' => 'South Asia',
                'region_id' => 64,
                'periodization_scheme' => 'South Asian',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Urban planning, undeciphered script, advanced drainage',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Decline of major cities',
                'historiographical_notes' => 'Causes of decline debated; climate change and river shifts likely',
                'value_judgments' => null,
                'color_hex' => '#CD7F32',
            ],
            [
                'period_id' => 81,
                'name' => 'Vedic Period',
                'alternative_names' => null,
                'start_date' => '-1500',
                'end_date' => '-500',
                'date_precision' => 'approximate',
                'geographic_scope' => 'South Asia',
                'region_id' => 65,
                'periodization_scheme' => 'South Asian',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Composition of Vedas, caste system emergence, Iron Age transition',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => 'Indo-Aryan migration/invasion debate remains contentious',
                'value_judgments' => null,
                'color_hex' => '#D4AC0D',
            ],
            [
                'period_id' => 82,
                'name' => 'Mahajanapadas',
                'alternative_names' => $this->textArray(['Sixteen Great Kingdoms']),
                'start_date' => '-600',
                'end_date' => '-345',
                'date_precision' => 'approximate',
                'geographic_scope' => 'South Asia',
                'region_id' => 65,
                'periodization_scheme' => 'South Asian',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Sixteen major kingdoms, rise of Buddhism and Jainism, urbanization',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Rise of Nanda Empire',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#F39C12',
            ],
            [
                'period_id' => 83,
                'name' => 'Maurya Empire',
                'alternative_names' => $this->textArray(['Mauryan period']),
                'start_date' => '-322',
                'end_date' => '-185',
                'date_precision' => 'conventional',
                'geographic_scope' => 'South Asia',
                'region_id' => 52,
                'periodization_scheme' => 'South Asian',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'First pan-Indian empire, Ashoka, spread of Buddhism',
                'conventional_start_event' => 'Chandragupta defeats Nanda',
                'conventional_end_event' => 'Assassination of Brihadratha',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#E67E22',
            ],

            // ══════════════════════════════════════════════
            // MESOAMERICAN
            // ══════════════════════════════════════════════
            [
                'period_id' => 90,
                'name' => 'Preclassic / Formative',
                'alternative_names' => $this->textArray(['Formative period']),
                'start_date' => '-2000',
                'end_date' => '250',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Mesoamerica',
                'region_id' => 81,
                'periodization_scheme' => 'Mesoamerican',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Olmec civilization, early writing, monumental architecture',
                'conventional_start_event' => null,
                'conventional_end_event' => null,
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#6B8E23',
            ],
            [
                'period_id' => 91,
                'name' => 'Classic',
                'alternative_names' => $this->textArray(['Classic Mesoamerican period']),
                'start_date' => '250',
                'end_date' => '900',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Mesoamerica',
                'region_id' => 81,
                'periodization_scheme' => 'Mesoamerican',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Maya peak, Teotihuacan, elaborate writing and astronomy',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Classic Maya collapse',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#228B22',
            ],
            [
                'period_id' => 92,
                'name' => 'Postclassic',
                'alternative_names' => $this->textArray(['Postclassic Mesoamerican period']),
                'start_date' => '900',
                'end_date' => '1521',
                'date_precision' => 'approximate',
                'geographic_scope' => 'Mesoamerica',
                'region_id' => 81,
                'periodization_scheme' => 'Mesoamerican',
                'parent_period_id' => null,
                'depth_level' => 0,
                'defining_characteristics' => 'Toltec, Aztec, increased militarism and long-distance trade',
                'conventional_start_event' => null,
                'conventional_end_event' => 'Spanish conquest of Tenochtitlan',
                'historiographical_notes' => null,
                'value_judgments' => null,
                'color_hex' => '#2E8B57',
            ],
        ];
    }
}
