<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReligiousTraditionSeeder extends Seeder
{
    public function run(): void
    {
        $table = 'ref_religious_traditions';

        // Disable FK checks for self-referencing parent_tradition_id
        DB::statement('ALTER TABLE ref_religious_traditions DISABLE TRIGGER ALL');
        DB::table($table)->truncate();

        $traditions = $this->buildTraditionTree();
        $sort = 0;

        foreach ($traditions as $tradition) {
            $tradition['sort_order'] = ++$sort;
            DB::table($table)->insert($tradition);
        }

        DB::statement('ALTER TABLE ref_religious_traditions ENABLE TRIGGER ALL');
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function buildTraditionTree(): array
    {
        return [
            // ══════════════════════════════════════════════
            // ABRAHAMIC TRADITIONS
            // ══════════════════════════════════════════════
            [
                'tradition_id' => 1,
                'name' => 'Abrahamic Traditions',
                'parent_tradition_id' => null,
                'depth_level' => 0,
                'origin_date' => '-2000~',
                'origin_region' => 'Near East',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#2E86C1',
            ],
            // ── Judaism ────────────────────────
            [
                'tradition_id' => 2,
                'name' => 'Judaism',
                'parent_tradition_id' => 1,
                'depth_level' => 1,
                'origin_date' => '-1200~',
                'origin_region' => 'Levant',
                'founder' => 'Abraham / Moses (traditional)',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1A5276',
            ],
            [
                'tradition_id' => 3,
                'name' => 'Second Temple Judaism',
                'parent_tradition_id' => 2,
                'depth_level' => 2,
                'origin_date' => '-516',
                'origin_region' => 'Judea',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1A5276',
            ],
            [
                'tradition_id' => 4,
                'name' => 'Rabbinic Judaism',
                'parent_tradition_id' => 2,
                'depth_level' => 2,
                'origin_date' => '70~',
                'origin_region' => 'Roman Palestine',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1A5276',
            ],
            [
                'tradition_id' => 5,
                'name' => 'Karaite Judaism',
                'parent_tradition_id' => 2,
                'depth_level' => 2,
                'origin_date' => '760~',
                'origin_region' => 'Mesopotamia',
                'founder' => 'Anan ben David',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1A5276',
            ],
            // ── Christianity ───────────────────
            [
                'tradition_id' => 10,
                'name' => 'Christianity',
                'parent_tradition_id' => 1,
                'depth_level' => 1,
                'origin_date' => '30~',
                'origin_region' => 'Roman Palestine',
                'founder' => 'Jesus of Nazareth',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#A93226',
            ],
            [
                'tradition_id' => 11,
                'name' => 'Pre-Nicene Christianity',
                'parent_tradition_id' => 10,
                'depth_level' => 2,
                'origin_date' => '30~',
                'origin_region' => 'Roman Empire',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#CB4335',
            ],
            [
                'tradition_id' => 12,
                'name' => 'Oriental Orthodoxy',
                'parent_tradition_id' => 10,
                'depth_level' => 2,
                'origin_date' => '451',
                'origin_region' => 'Egypt, Ethiopia, Armenia, Syria',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#CB4335',
            ],
            [
                'tradition_id' => 13,
                'name' => 'Eastern Orthodoxy',
                'parent_tradition_id' => 10,
                'depth_level' => 2,
                'origin_date' => '1054',
                'origin_region' => 'Byzantine Empire',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#CB4335',
            ],
            [
                'tradition_id' => 14,
                'name' => 'Roman Catholicism',
                'parent_tradition_id' => 10,
                'depth_level' => 2,
                'origin_date' => '1054',
                'origin_region' => 'Rome, Western Europe',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#CB4335',
            ],
            [
                'tradition_id' => 15,
                'name' => 'Protestantism',
                'parent_tradition_id' => 10,
                'depth_level' => 2,
                'origin_date' => '1517',
                'origin_region' => 'Germany',
                'founder' => 'Martin Luther',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#E74C3C',
            ],
            [
                'tradition_id' => 16,
                'name' => 'Lutheranism',
                'parent_tradition_id' => 15,
                'depth_level' => 3,
                'origin_date' => '1517',
                'origin_region' => 'Germany',
                'founder' => 'Martin Luther',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#E74C3C',
            ],
            [
                'tradition_id' => 17,
                'name' => 'Calvinism / Reformed',
                'parent_tradition_id' => 15,
                'depth_level' => 3,
                'origin_date' => '1536',
                'origin_region' => 'Geneva, Switzerland',
                'founder' => 'John Calvin',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#E74C3C',
            ],
            [
                'tradition_id' => 18,
                'name' => 'Anglicanism',
                'parent_tradition_id' => 15,
                'depth_level' => 3,
                'origin_date' => '1534',
                'origin_region' => 'England',
                'founder' => 'Henry VIII (political); Thomas Cranmer (theological)',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#E74C3C',
            ],
            [
                'tradition_id' => 19,
                'name' => 'Restorationist Movements',
                'parent_tradition_id' => 10,
                'depth_level' => 2,
                'origin_date' => '1800~',
                'origin_region' => 'United States',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#F1948A',
            ],
            // ── Islam ──────────────────────────
            [
                'tradition_id' => 20,
                'name' => 'Islam',
                'parent_tradition_id' => 1,
                'depth_level' => 1,
                'origin_date' => '610',
                'origin_region' => 'Arabian Peninsula',
                'founder' => 'Muhammad',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#27AE60',
            ],
            [
                'tradition_id' => 21,
                'name' => 'Sunni',
                'parent_tradition_id' => 20,
                'depth_level' => 2,
                'origin_date' => '632~',
                'origin_region' => 'Arabia',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#2ECC71',
            ],
            [
                'tradition_id' => 22,
                'name' => 'Hanafi',
                'parent_tradition_id' => 21,
                'depth_level' => 3,
                'origin_date' => '767~',
                'origin_region' => 'Kufa, Iraq',
                'founder' => 'Abu Hanifa',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#2ECC71',
            ],
            [
                'tradition_id' => 23,
                'name' => 'Maliki',
                'parent_tradition_id' => 21,
                'depth_level' => 3,
                'origin_date' => '795~',
                'origin_region' => 'Medina',
                'founder' => 'Malik ibn Anas',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#2ECC71',
            ],
            [
                'tradition_id' => 24,
                'name' => "Shafi'i",
                'parent_tradition_id' => 21,
                'depth_level' => 3,
                'origin_date' => '820~',
                'origin_region' => 'Egypt',
                'founder' => "al-Shafi'i",
                'tradition_type' => 'monotheistic',
                'color_hex' => '#2ECC71',
            ],
            [
                'tradition_id' => 25,
                'name' => 'Hanbali',
                'parent_tradition_id' => 21,
                'depth_level' => 3,
                'origin_date' => '855~',
                'origin_region' => 'Baghdad',
                'founder' => 'Ahmad ibn Hanbal',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#2ECC71',
            ],
            [
                'tradition_id' => 26,
                'name' => 'Shia',
                'parent_tradition_id' => 20,
                'depth_level' => 2,
                'origin_date' => '632~',
                'origin_region' => 'Arabia',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1ABC9C',
            ],
            [
                'tradition_id' => 27,
                'name' => 'Twelver',
                'parent_tradition_id' => 26,
                'depth_level' => 3,
                'origin_date' => '874~',
                'origin_region' => 'Iraq',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1ABC9C',
            ],
            [
                'tradition_id' => 28,
                'name' => 'Ismaili',
                'parent_tradition_id' => 26,
                'depth_level' => 3,
                'origin_date' => '765~',
                'origin_region' => 'Arabia / Persia',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1ABC9C',
            ],
            [
                'tradition_id' => 29,
                'name' => 'Zaydi',
                'parent_tradition_id' => 26,
                'depth_level' => 3,
                'origin_date' => '740~',
                'origin_region' => 'Yemen',
                'founder' => 'Zayd ibn Ali',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1ABC9C',
            ],
            [
                'tradition_id' => 30,
                'name' => 'Ibadi',
                'parent_tradition_id' => 20,
                'depth_level' => 2,
                'origin_date' => '680~',
                'origin_region' => 'Basra, Iraq',
                'founder' => 'Abdullah ibn Ibad',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#16A085',
            ],
            [
                'tradition_id' => 31,
                'name' => 'Sufi Orders',
                'parent_tradition_id' => 20,
                'depth_level' => 2,
                'origin_date' => '800~',
                'origin_region' => 'Islamic world',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#148F77',
            ],
            // ── Other Abrahamic ────────────────
            [
                'tradition_id' => 32,
                'name' => 'Mandaeism',
                'parent_tradition_id' => 1,
                'depth_level' => 1,
                'origin_date' => '100~',
                'origin_region' => 'Mesopotamia',
                'founder' => 'John the Baptist (claimed)',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#5DADE2',
            ],
            [
                'tradition_id' => 33,
                'name' => 'Druze',
                'parent_tradition_id' => 1,
                'depth_level' => 1,
                'origin_date' => '1017',
                'origin_region' => 'Egypt / Levant',
                'founder' => 'Hamza ibn Ali',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#85C1E9',
            ],
            [
                'tradition_id' => 34,
                'name' => "Baha'i",
                'parent_tradition_id' => 1,
                'depth_level' => 1,
                'origin_date' => '1863',
                'origin_region' => 'Persia',
                'founder' => "Baha'u'llah",
                'tradition_type' => 'monotheistic',
                'color_hex' => '#AED6F1',
            ],

            // ══════════════════════════════════════════════
            // DHARMIC TRADITIONS
            // ══════════════════════════════════════════════
            [
                'tradition_id' => 40,
                'name' => 'Dharmic Traditions',
                'parent_tradition_id' => null,
                'depth_level' => 0,
                'origin_date' => '-1500~',
                'origin_region' => 'South Asia',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#E67E22',
            ],
            // ── Hinduism ───────────────────────
            [
                'tradition_id' => 41,
                'name' => 'Hinduism',
                'parent_tradition_id' => 40,
                'depth_level' => 1,
                'origin_date' => '-1500~',
                'origin_region' => 'South Asia',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#D35400',
            ],
            [
                'tradition_id' => 42,
                'name' => 'Vaishnavism',
                'parent_tradition_id' => 41,
                'depth_level' => 2,
                'origin_date' => '-500~',
                'origin_region' => 'South Asia',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#D35400',
            ],
            [
                'tradition_id' => 43,
                'name' => 'Shaivism',
                'parent_tradition_id' => 41,
                'depth_level' => 2,
                'origin_date' => '-500~',
                'origin_region' => 'South Asia',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#D35400',
            ],
            [
                'tradition_id' => 44,
                'name' => 'Shaktism',
                'parent_tradition_id' => 41,
                'depth_level' => 2,
                'origin_date' => '-500~',
                'origin_region' => 'South Asia',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#D35400',
            ],
            [
                'tradition_id' => 45,
                'name' => 'Smartism',
                'parent_tradition_id' => 41,
                'depth_level' => 2,
                'origin_date' => '800~',
                'origin_region' => 'South Asia',
                'founder' => 'Adi Shankara',
                'tradition_type' => 'polytheistic',
                'color_hex' => '#D35400',
            ],
            // ── Buddhism ───────────────────────
            [
                'tradition_id' => 50,
                'name' => 'Buddhism',
                'parent_tradition_id' => 40,
                'depth_level' => 1,
                'origin_date' => '-500~',
                'origin_region' => 'South Asia (Gangetic Plain)',
                'founder' => 'Siddhartha Gautama (the Buddha)',
                'tradition_type' => 'nontheistic',
                'color_hex' => '#F39C12',
            ],
            [
                'tradition_id' => 51,
                'name' => 'Theravada',
                'parent_tradition_id' => 50,
                'depth_level' => 2,
                'origin_date' => '-300~',
                'origin_region' => 'Sri Lanka, Southeast Asia',
                'founder' => null,
                'tradition_type' => 'nontheistic',
                'color_hex' => '#F39C12',
            ],
            [
                'tradition_id' => 52,
                'name' => 'Mahayana',
                'parent_tradition_id' => 50,
                'depth_level' => 2,
                'origin_date' => '-100~',
                'origin_region' => 'India, Central Asia, East Asia',
                'founder' => null,
                'tradition_type' => 'nontheistic',
                'color_hex' => '#F1C40F',
            ],
            [
                'tradition_id' => 53,
                'name' => 'Chan / Zen',
                'parent_tradition_id' => 52,
                'depth_level' => 3,
                'origin_date' => '500~',
                'origin_region' => 'China',
                'founder' => 'Bodhidharma (traditional)',
                'tradition_type' => 'nontheistic',
                'color_hex' => '#F1C40F',
            ],
            [
                'tradition_id' => 54,
                'name' => 'Pure Land',
                'parent_tradition_id' => 52,
                'depth_level' => 3,
                'origin_date' => '400~',
                'origin_region' => 'China',
                'founder' => 'Huiyuan',
                'tradition_type' => 'nontheistic',
                'color_hex' => '#F1C40F',
            ],
            [
                'tradition_id' => 55,
                'name' => 'Nichiren',
                'parent_tradition_id' => 52,
                'depth_level' => 3,
                'origin_date' => '1253',
                'origin_region' => 'Japan',
                'founder' => 'Nichiren',
                'tradition_type' => 'nontheistic',
                'color_hex' => '#F1C40F',
            ],
            [
                'tradition_id' => 56,
                'name' => 'Vajrayana',
                'parent_tradition_id' => 50,
                'depth_level' => 2,
                'origin_date' => '500~',
                'origin_region' => 'India, Tibet',
                'founder' => null,
                'tradition_type' => 'nontheistic',
                'color_hex' => '#E67E22',
            ],
            // ── Jainism ────────────────────────
            [
                'tradition_id' => 60,
                'name' => 'Jainism',
                'parent_tradition_id' => 40,
                'depth_level' => 1,
                'origin_date' => '-600~',
                'origin_region' => 'South Asia (Bihar)',
                'founder' => 'Mahavira',
                'tradition_type' => 'nontheistic',
                'color_hex' => '#DC7633',
            ],
            [
                'tradition_id' => 61,
                'name' => 'Digambara',
                'parent_tradition_id' => 60,
                'depth_level' => 2,
                'origin_date' => '-300~',
                'origin_region' => 'South India',
                'founder' => null,
                'tradition_type' => 'nontheistic',
                'color_hex' => '#DC7633',
            ],
            [
                'tradition_id' => 62,
                'name' => 'Shvetambara',
                'parent_tradition_id' => 60,
                'depth_level' => 2,
                'origin_date' => '-300~',
                'origin_region' => 'Western India',
                'founder' => null,
                'tradition_type' => 'nontheistic',
                'color_hex' => '#DC7633',
            ],
            // ── Sikhism ────────────────────────
            [
                'tradition_id' => 63,
                'name' => 'Sikhism',
                'parent_tradition_id' => 40,
                'depth_level' => 1,
                'origin_date' => '1469',
                'origin_region' => 'Punjab',
                'founder' => 'Guru Nanak',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#CA6F1E',
            ],

            // ══════════════════════════════════════════════
            // EAST ASIAN TRADITIONS
            // ══════════════════════════════════════════════
            [
                'tradition_id' => 70,
                'name' => 'East Asian Traditions',
                'parent_tradition_id' => null,
                'depth_level' => 0,
                'origin_date' => '-500~',
                'origin_region' => 'East Asia',
                'founder' => null,
                'tradition_type' => 'philosophical',
                'color_hex' => '#8E44AD',
            ],
            [
                'tradition_id' => 71,
                'name' => 'Confucianism',
                'parent_tradition_id' => 70,
                'depth_level' => 1,
                'origin_date' => '-500~',
                'origin_region' => 'China',
                'founder' => 'Confucius',
                'tradition_type' => 'philosophical',
                'color_hex' => '#9B59B6',
            ],
            [
                'tradition_id' => 72,
                'name' => 'Neo-Confucianism',
                'parent_tradition_id' => 71,
                'depth_level' => 2,
                'origin_date' => '1000~',
                'origin_region' => 'China',
                'founder' => 'Zhu Xi',
                'tradition_type' => 'philosophical',
                'color_hex' => '#9B59B6',
            ],
            [
                'tradition_id' => 73,
                'name' => 'Taoism',
                'parent_tradition_id' => 70,
                'depth_level' => 1,
                'origin_date' => '-400~',
                'origin_region' => 'China',
                'founder' => 'Laozi (traditional)',
                'tradition_type' => 'philosophical',
                'color_hex' => '#AF7AC5',
            ],
            [
                'tradition_id' => 74,
                'name' => 'Philosophical Taoism',
                'parent_tradition_id' => 73,
                'depth_level' => 2,
                'origin_date' => '-400~',
                'origin_region' => 'China',
                'founder' => 'Laozi',
                'tradition_type' => 'philosophical',
                'color_hex' => '#AF7AC5',
            ],
            [
                'tradition_id' => 75,
                'name' => 'Religious Taoism',
                'parent_tradition_id' => 73,
                'depth_level' => 2,
                'origin_date' => '142~',
                'origin_region' => 'China',
                'founder' => 'Zhang Daoling',
                'tradition_type' => 'polytheistic',
                'color_hex' => '#AF7AC5',
            ],
            [
                'tradition_id' => 76,
                'name' => 'Shinto',
                'parent_tradition_id' => 70,
                'depth_level' => 1,
                'origin_date' => '-500~',
                'origin_region' => 'Japan',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#BB8FCE',
            ],

            // ══════════════════════════════════════════════
            // IRANIAN / ZOROASTRIAN
            // ══════════════════════════════════════════════
            [
                'tradition_id' => 80,
                'name' => 'Iranian / Zoroastrian',
                'parent_tradition_id' => null,
                'depth_level' => 0,
                'origin_date' => '-1500~',
                'origin_region' => 'Iranian Plateau',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#1ABC9C',
            ],
            [
                'tradition_id' => 81,
                'name' => 'Zoroastrianism',
                'parent_tradition_id' => 80,
                'depth_level' => 1,
                'origin_date' => '-1500~',
                'origin_region' => 'Iranian Plateau',
                'founder' => 'Zarathustra',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#17A589',
            ],
            [
                'tradition_id' => 82,
                'name' => 'Manichaeism',
                'parent_tradition_id' => 80,
                'depth_level' => 1,
                'origin_date' => '240~',
                'origin_region' => 'Mesopotamia',
                'founder' => 'Mani',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#48C9B0',
            ],
            [
                'tradition_id' => 83,
                'name' => 'Mazdakism',
                'parent_tradition_id' => 80,
                'depth_level' => 1,
                'origin_date' => '500~',
                'origin_region' => 'Sasanian Persia',
                'founder' => 'Mazdak',
                'tradition_type' => 'monotheistic',
                'color_hex' => '#48C9B0',
            ],
            [
                'tradition_id' => 84,
                'name' => 'Zurvanism',
                'parent_tradition_id' => 80,
                'depth_level' => 1,
                'origin_date' => '-400~',
                'origin_region' => 'Persia',
                'founder' => null,
                'tradition_type' => 'monotheistic',
                'color_hex' => '#48C9B0',
            ],

            // ══════════════════════════════════════════════
            // ANCIENT / RECONSTRUCTED
            // ══════════════════════════════════════════════
            [
                'tradition_id' => 90,
                'name' => 'Ancient / Reconstructed',
                'parent_tradition_id' => null,
                'depth_level' => 0,
                'origin_date' => '-3000~',
                'origin_region' => 'Global',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#95A5A6',
            ],
            [
                'tradition_id' => 91,
                'name' => 'Mesopotamian Religion',
                'parent_tradition_id' => 90,
                'depth_level' => 1,
                'origin_date' => '-3500~',
                'origin_region' => 'Mesopotamia',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#7F8C8D',
            ],
            [
                'tradition_id' => 92,
                'name' => 'Egyptian Religion',
                'parent_tradition_id' => 90,
                'depth_level' => 1,
                'origin_date' => '-3000~',
                'origin_region' => 'Egypt',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#7F8C8D',
            ],
            [
                'tradition_id' => 93,
                'name' => 'Greek Religion',
                'parent_tradition_id' => 90,
                'depth_level' => 1,
                'origin_date' => '-800~',
                'origin_region' => 'Greece',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#7F8C8D',
            ],
            [
                'tradition_id' => 94,
                'name' => 'Roman Religion',
                'parent_tradition_id' => 90,
                'depth_level' => 1,
                'origin_date' => '-700~',
                'origin_region' => 'Italy',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#7F8C8D',
            ],
            [
                'tradition_id' => 95,
                'name' => 'Norse Religion',
                'parent_tradition_id' => 90,
                'depth_level' => 1,
                'origin_date' => '-500~',
                'origin_region' => 'Scandinavia',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#7F8C8D',
            ],
            [
                'tradition_id' => 96,
                'name' => 'Celtic Religion',
                'parent_tradition_id' => 90,
                'depth_level' => 1,
                'origin_date' => '-500~',
                'origin_region' => 'Western Europe',
                'founder' => null,
                'tradition_type' => 'polytheistic',
                'color_hex' => '#7F8C8D',
            ],

            // ══════════════════════════════════════════════
            // INDIGENOUS / TRADITIONAL
            // ══════════════════════════════════════════════
            [
                'tradition_id' => 100,
                'name' => 'Indigenous / Traditional',
                'parent_tradition_id' => null,
                'depth_level' => 0,
                'origin_date' => null,
                'origin_region' => 'Global',
                'founder' => null,
                'tradition_type' => 'animistic',
                'color_hex' => '#784212',
            ],
            [
                'tradition_id' => 101,
                'name' => 'Animistic Traditions',
                'parent_tradition_id' => 100,
                'depth_level' => 1,
                'origin_date' => null,
                'origin_region' => 'Global',
                'founder' => null,
                'tradition_type' => 'animistic',
                'color_hex' => '#A04000',
            ],
            [
                'tradition_id' => 102,
                'name' => 'Shamanic Traditions',
                'parent_tradition_id' => 100,
                'depth_level' => 1,
                'origin_date' => null,
                'origin_region' => 'Global (especially Siberia, Americas)',
                'founder' => null,
                'tradition_type' => 'animistic',
                'color_hex' => '#A04000',
            ],
            [
                'tradition_id' => 103,
                'name' => 'Ancestor Worship Traditions',
                'parent_tradition_id' => 100,
                'depth_level' => 1,
                'origin_date' => null,
                'origin_region' => 'Global (especially East Asia, Africa)',
                'founder' => null,
                'tradition_type' => 'animistic',
                'color_hex' => '#A04000',
            ],
        ];
    }
}
